app/assets/stylesheets/blacklight.scss, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_show_default.html.erb
Instead of displaying the fcrepo URIs for related and member objects, display the titles of those objects and link to their catalog page in Archelon.
https://issues.umd.edu/browse/LIBHYDRA-53
=> LIBHYDRA-53. Display related and member objects' titles as links.

app/views/mirador/_show.html.erb
See also https://issues.umd.edu/browse/LIBFCREPO-174 for the update in pcdm-manifests to accept a prefixed identifier.
https://issues.umd.edu/browse/LIBHYDRA-65
=> LIBHYDRA-65. Prepend "fcrepo:" to the PCDM manifest path.

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_show_sidebar.html.erb
* Removed "Fedora URL" from the fields shown in the document body.
* Changed the encoded_id helper to non-destructively strip the FEDORA_BASE_URL prefix from the document id.
* Added a custom _show_sidebar partial (copied from Blacklight and modified to add the "View in Fedora" link)
https://issues.umd.edu/browse/LIBHYDRA-64
=> LIBHYDRA-64. Added "View in Fedora" link to sidebar.

app/helpers/application_helper.rb, app/views/catalog/_show_sidebar.html.erb
Also changed "View in Fedora" link to point to the fcr:metadata for the resource.
https://issues.umd.edu/browse/LIBHYDRA-67
=> LIBHYDRA-67. Added "Download" link for binaries.

app/helpers/application_helper.rb, app/views/catalog/_show_default.html.erb
In addition, sort by their title and display a badge with the number of each type next to the component type header.
https://issues.umd.edu/browse/LIBFCREPO-250
=> LIBFCREPO-250. Display members grouped by their component type.

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/views/mirador/_show.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/vagrant.rb, env_example
Uses the Addressable::Template URI template gem to construct the mirador static viewer URL for the given document and query. Mirador static version is set through an environment variable instead of being hardcoded into the view.
https://issues.umd.edu/browse/LIBHYDRA-99
=> LIBHYDRA-99. Added a mirador_viewer_url helper method.

app/assets/stylesheets/application.scss, app/views/catalog/_show_default.html.erb, app/views/mirador/_show.html.erb
Includes a "skip link" to the metadata. This link required a data-turbolinks="false" attribute to stop TurboLinks from doing another GET request for the in-page link. See also https://github.com/turbolinks/turbolinks/issues/75.
https://issues.umd.edu/browse/LIBHYDRA-103
=> LIBHYDRA-103. Move image viewer above metadata.

config/routes.rb
By default, Rails does not allow dynamic segments in a URL to contain a
period (.) as it is typically used to specify the expected format of
the response.
The Download URL controller contains a route that may contain a URL,
which has periods in the hostname portion. The "generate_download_url"
route was updated to allow periods.
https://issues.umd.edu/browse/LIBHYDRA-111
=> LIBHYDRA-111 Enable Download URL routes to contain a period

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb
Also strip out "{SOFT HYPHEN}{NEWLINE}" sequences when displaying the snippets, so we don't get ugly word breaks in the middle of words on the result page.
https://issues.umd.edu/browse/LIBHYDRA-106
=> LIBHYDRA-106. Increase highlighted snippet size.

app/controllers/catalog_controller.rb, app/controllers/retrieve_controller.rb, app/views/retrieve/retrieve.html.erb, config/application.rb, config/environments/vagrant.rb
Default to doing SSL peer verification of certificates, but disable it for the Vagrant environment, since fcrepolocal uses a self-signed certificate. Also corrected a mismatched tag in the retrieve view.
https://issues.umd.edu/browse/LIBHYDRA-113
=> LIBHYDRA-113. SSL configuration for downloads.

app/controllers/retrieve_controller.rb, config/application.rb
This adds a configuration to point to the SSL ca file, which was not
being found by OpenSSL::SSL::SSLContext. This can be set using a ENV['SSL_CERT_FILE']
variable or it looks at '/etc/ssl/certs/ca-bundle.crt' by default
https://issues.umd.edu/browse/LIBHYDRA-124
=> LIBHYDRA-124 Point to ca_file in SSL context

app/controllers/catalog_controller.rb, config/locales/en.yml, test/controllers/catalog_controller_test.rb
This rescues and redirects if blacklight cannot connect to solr. The
catalog controller will redirect to the about page. User pages will also
still work.
=> LIBHYDRA-85 Rescue if Blacklight cannot connect

app/helpers/application_helper.rb
The PCDM manifests app now uses shortened URIs in the manifests, so when Mirador tries to set the current canvas based on comparing URLs, it never matches to the full URL and was showing page 1 always.
https://issues.umd.edu/browse/LIBHYDRA-137
=> LIBHYDRA-137. Shorten the manifest ID passed to Mirador.

app/controllers/catalog_controller.rb
https://issues.umd.edu/browse/LIBHYDRA-135
=> LIBHYDRA-135. Moved RDF type to bottom of metadata details.

Gemfile, Gemfile.lock, app/controllers/cas_users_controller.rb, app/views/cas_users/index.html.erb, app/views/cas_users/show.html.erb, app/views/cas_users/show_history.html.erb, config/environments/development.rb, config/environments/production.rb, config/routes.rb, env_example
Displays the audit records where the user is named as an agent. Defaults to displaying 90 days back, can be set to a different value via a form and query params.
https://issues.umd.edu/browse/LIBHYDRA-158
=> LIBHYDRA-158. Add a user history page.

Jenkinsfile, test/controllers/download_urls_controller_test.rb, test/integration/cas_authorization_test.rb, test/integration/download_urls_index_test.rb, test/integration/user_impersonation_test.rb, test/test_helper.rb
Added "rspec-mocks" gem, and added stubs for LDAP and Solr calls in the tests.
This enables all the tests to pass on Jenkins.
Note: The code also uses "minitest" mocks/stubs is some tests, but it did not appear that "minitest" was capable enough to be used for all the places that needed to be stubbed.
https://issues.umd.edu/browse/LIBHYDRA-185
=> LIBHYDRA-185. Enable tests to run on Jenkins

Dockerfile
Configured the Dockerfile to remove a line from the /etc/ssl/openssl.cnf
configuration file, to make it less strict about the SSL certificates
of servers it contacts.
This is intended to be a temporary fix until the SSL certificate on
https://login.umd.edu is updated.
https://issues.umd.edu/browse/LIBHYDRA-186
=> LIBHYDRA-186. Added workaround for https://login.umd.edu SSL issue

README.md
Added information to the README.md about CVE-2015-9284, and that no
action is needed as the application uses CAS for authentication.
https://issues.umd.edu/browse/LIBHYDRA-180
=> LIBHYDRA-180. Added information to README.md about CVE-2015-9284

README.md, app/models/cas_user.rb, app/models/ldap_user_attributes.rb, config/initializers/ldap.rb, config/ldap.yml, test/integration/cas_authorization_test.rb, test/models/ldap_user_attributes_test.rb
Added LDAP_OVERRIDE environment variable to skip LDAP searches in the development environment, and use the value of the variable as the user type.
The name of the user will be the cas_directory_id the user logged in with.
Also refactored LDAP-related code out of CasUser class and into LdapUserAttributes.
https://issues.umd.edu/browse/LIBHYDRA-190
=> LIBHYDRA-190. Added LDAP_OVERRIDE environment variable

app/controllers/bookmarks_controller.rb, app/models/export_job.rb, app/models/search_builder.rb, app/views/catalog/_select_box.erb, config/locales/en.yml
* Remove checkbox from non-exportable content models
* The "select all in the search" function adds a filter query to only return exportable types
https://issues.umd.edu/browse/LIBHYDRA-209
=> LIBHYDRA-209. Only allow exportable items to be selected.

app/controllers/bookmarks_controller.rb
When handling the "select all on page" request, if the document_ids param is not present assume there are no candidate ids to be selected and use an empty list for the item_ids array.
https://issues.umd.edu/browse/LIBHYDRA-212
=> LIBHYDRA-212. Default to empty list of document ids.

app/models/individual.rb, app/models/type.rb, app/models/vocabulary.rb, test/models/individual_test.rb, test/models/type_test.rb, test/models/vocabulary_test.rb
Vocabulary identifiers must be globally unique. Type and individual identifiers must be unique within their vocabulary.
https://issues.umd.edu/browse/LIBHYDRA-226
=> LIBHYDRA-226. Add uniqueness constraints on identifiers.

app/views/individuals/_form.html.erb, app/views/individuals/edit.html.erb, app/views/individuals/new.html.erb, app/views/individuals/show.html.erb, app/views/types/_form.html.erb, app/views/types/edit.html.erb, app/views/types/new.html.erb, app/views/types/show.html.erb, app/views/vocabularies/_form.html.erb, app/views/vocabularies/edit.html.erb, app/views/vocabularies/index.html.erb, app/views/vocabularies/new.html.erb, app/views/vocabularies/show.html.erb
Updated the index, show, new, and edit pages of the
Vocabulary, Individual, Type models.
Among the changes:
* Changed "Back" link to "Cancel"
* Changed "Destroy" button to "Delete"
* Made "New" button color consistent across pages
https://issues.umd.edu/browse/LIBHYDRA-234
=> LIBHYDRA-234. Bootstrap GUI updates to Vocabulary/Individual/Type pages

app/assets/stylesheets/custom.css, app/views/individuals/_form.html.erb, app/views/individuals/edit.html.erb, app/views/individuals/new.html.erb, app/views/individuals/show.html.erb, app/views/types/_form.html.erb, app/views/types/edit.html.erb, app/views/types/new.html.erb, app/views/types/show.html.erb, app/views/vocabularies/_form.html.erb, app/views/vocabularies/edit.html.erb, app/views/vocabularies/index.html.erb, app/views/vocabularies/new.html.erb, app/views/vocabularies/show.html.erb
Modified the GUI to show the "Classes" and "Terms" into two side-by-side
panels.
Also modified the panel headers to link to their respective index pages.
https://issues.umd.edu/browse/LIBHYDRA-236
=> LIBHYDRA-236. Moved vocabulary classes and terms into two columns

app/controllers/individuals_controller.rb, app/controllers/types_controller.rb, app/controllers/vocabularies_controller.rb
Modified the Vocabularies, Individuals, and Types controllers to use
I18n value in flash notices for consistency in the GUI.
https://issues.umd.edu/browse/LIBHYDRA-239
=> LIBHYDRA-239. Modified controllers to use I18n in flash notices

app/models/individual.rb, app/views/individuals/show.html.erb, config/initializers/same_as_abbreviations.rb, config/same_as_abbreviations.yml
The lookup table is in config/same_as_abbreviations.yml, and is read at startup.
https://issues.umd.edu/browse/LIBHYDRA-237
=> LIBHYDRA-237. Display a source next to the label for terms.

app/assets/stylesheets/custom.css, app/views/individuals/_form.html.erb, app/views/types/_form.html.erb, app/views/vocabularies/_form.html.erb, config/locales/en.yml
On the forms, added tooltip text to the "Identifier" and "URI" labels
that appear when the mouse is hovered over the labels. The labels
display with a dotted underline to indicate that a tooltip is
available.
https://issues.umd.edu/browse/LIBHYDRA-235
=> LIBHYDRA-235. Added tooltip text to "Identifier" and "URI" form labels

app/controllers/application_controller.rb, app/controllers/download_urls_controller.rb, app/controllers/vocabularies_controller.rb, test/controllers/download_urls_controller_test.rb
* If an ?identifier query param is passed to the vocabularies index controller method, search for the vocabulary by that identifier.
* Added a 404 response if a vocabulary cannot be found (by id or identifier)
https://issues.umd.edu/browse/LIBHYDRA-240
=> LIBHYDRA-240. Allow retrieval of a vocabulary by its identifier.

.gitignore, app/controllers/vocabularies_controller.rb, app/jobs/application_job.rb, app/jobs/publish_vocabulary_rdf_job.rb, app/jobs/unpublish_vocabulary_rdf_job.rb, app/models/vocabulary.rb, test/jobs/publish_vocabulary_rdf_job_test.rb, test/jobs/unpublish_vocabulary_rdf_job_test.rb
* formats: JSON-LD, Turtle, N-Triples
* when a vocabulary is created or updated, write out the RDF to the public/vocabularies directory
* delete published files when a vocabulary is destroyed
* publish/unpublish are handled asynchronously by ActiveJobs
https://issues.umd.edu/browse/LIBHYDRA-240
=> LIBHYDRA-230. Publish static RDF serialzations of vocabularies

.gitignore, app/models/vocabulary.rb, app/views/vocabularies/index.html.erb, config/initializers/vocabularies.rb, config/locales/en.yml, config/vocabularies.yml
* serve published vocabularies using Rails for development.
* supply the configuration for production via environment variables
https://issues.umd.edu/browse/LIBHYDRA-243
=> LIBHYDRA-243. Separate local authority URI from published vocab URI.

app/views/vocabularies/show.html.erb, config/locales/en.yml
Also swapped the order of the panels so that terms is to the left of (or on top of) classes, and is wider.
https://issues.umd.edu/browse/LIBHYDRA-246
=> LIBHYDRA-246. Add source to term list on vocabulary page.

app/models/group.rb, app/models/ldap_user_attributes.rb, test/integration/cas_authorization_test.rb, test/models/ldap_user_attributes_test.rb
Our LDAP server returns some (but not all) group DNs in all lowercase.
https://issues.umd.edu/browse/LIBHYDRA-247
=> LIBHYDRA-247. Check LDAP group DNs ignoring case.

app/models/individual.rb
Rails extends Ruby's blank? method to return true for nil.
https://issues.umd.edu/browse/LIBHYDRA-249
=> LIBHYDRA-249. Use blank? instead of empty? to catch nils.

app/models/vocabulary.rb, lib/tasks/vocab.rake
Call this from the rake task to publish the vocabulary after import.
https://issues.umd.edu/browse/LIBHYDRA-250
=> LIBHYDRA-250. Added :all shortcut to publish all vocab RDF formats.

app/controllers/ping_controller.rb, config/routes.rb, test/controllers/ping_controller_test.rb
Implemented in similar manner to annual-staffing-request (see LIBITD-691
and LIBITD-1002), in which a "/ping" endpoint is provided that does not
require authentication, and tests whether is application is connected to
the database (via "ActiveRecord::Base.connected?")
https://issues.umd.edu/browse/LIBHYDRA-221
=> LIBHYDRA-221. Implemented unauthenticated "/ping" endpoint

app/controllers/export_jobs_controller.rb, app/models/export_job.rb, app/services/stomp_client.rb, config/stomp.yml, test/services/stomp_client_test.rb
- changed from "ArchelonExport*" to "PlastronCommand", "PlastronJobId", and "PlastronArg-*"
- changed queue names to "plastron.jobs" and "plastron.jobs.completed"
- download URL is returned in the body of the message, along with other export stats
https://issues.umd.edu/browse/LIBHYDRA-259
=> LIBHYDRA-259. Use generic header and queue names.

app/controllers/export_jobs_controller.rb, app/models/export_job.rb, app/services/stomp_client.rb, config/stomp.yml, test/services/stomp_client_test.rb
Removed "export" from generic method and variable names.
https://issues.umd.edu/browse/LIBHYDRA-258
=> LIBHYDRA-258. Update job progress based on plastron.job.status messages.

app/assets/stylesheets/custom.css, app/controllers/import_jobs_controller.rb, app/models/import_job.rb, app/views/import_jobs/_import_job_validation_panel.erb, app/views/import_jobs/edit.html.erb, app/views/import_jobs/index.html.erb, app/views/import_jobs/show.html.erb, config/locales/en.yml, test/controllers/import_jobs_controller_test.rb
On the Import Job index page, converted the "status" field to a hyperlink that displays information about the import job.
https://issues.umd.edu/browse/LIBHYDRA-267
=> LIBHYDRA-267. Added hyperlink to "status" field on Import Job index page

app/assets/stylesheets/custom.css, app/controllers/import_jobs_controller.rb, app/models/import_job.rb, app/services/import_job_response.rb, app/views/import_jobs/_import_job_validation_panel.erb, app/views/import_jobs/edit.html.erb, app/views/import_jobs/index.html.erb, app/views/import_jobs/show.html.erb, config/locales/en.yml, test/controllers/import_jobs_controller_test.rb, test/services/import_job_response_test.rb
Added a collapsed "JSON" panel to the "Validation" panel for import
jobs, which shows pretty-printed JSON when uncollapsed.
"JSON" panel will not be displayed if there is no JSON to display
(for example, if a server error occurred).
https://issues.umd.edu/browse/LIBHYDRA-268
=> LIBHYDRA-268. Added a collapsed "JSON" panel to validation panel

app/controllers/import_jobs_controller.rb, app/models/import_job.rb, app/services/import_job_response.rb, app/services/stomp_client.rb, app/views/import_jobs/_import_job_validation_panel.erb, db/migrate/20200416134039_add_last_response_headers_to_import_job.rb, db/migrate/20200416134423_rename_last_response_to_last_response_body_in_import_job.rb, db/schema.rb, test/models/import_job_test.rb, test/services/import_job_response_test.rb
In "import_jobs" table, renamed "last_response" to "last_response_body", and added a "last_response_headers" field.
Refactored ImportJobResponse to include headers. Replaced "json_pretty_print" method with "headers_pretty_print" and "body_pretty_print" methods to give extra flexibility to the views about how to display the JSON in the GUI.
Added "last_response" method to ImportJob model to return an ImportJobResponse object. This should hopefully better insulate the model and controllers from changes in the import job message formats.
Added "headers_json" method to StompClient, to enable the headers to be stored in the database in JSON format, instead of Ruby serialization.
Modified "_import_job_validation_panel.erb" to display headers and body in the "JSON" subpanel.
Updated the tests …
=> LIBHYDRA-270. Refactored Import Jobs to store response headers

app/controllers/export_jobs_controller.rb, app/controllers/import_jobs_controller.rb
Replaced the "PlastronArg-username" argument in the "message_headers"
methods of the ImportJobsController and ExportJobsController with
"PlastronArg-on-behalf-of".
https://issues.umd.edu/browse/LIBHYDRA-271
=> LIBHYDRA-271. Modified to use "PlastronArg-on-behalf-of" header

app/controllers/export_jobs_controller.rb, app/models/ability.rb, test/controllers/export_jobs_controller_test.rb
Modified the export job downloads so that export files can only be
downloaded by the job owner and admins.
https://issues.umd.edu/browse/LIBHYDRA-278
=> LIBHYDRA-278. Added per-user authorization to export job downloads

app/controllers/vocabularies_controller.rb, app/models/vocabulary.rb, app/views/datatypes/_form.html.erb, app/views/individuals/_form.html.erb, app/views/types/_form.html.erb
Added "by_identifier" scope to Vocabulary model to enable vocabularies
to be easily sorted into alphabetical order by identifiers.
Updated controller and ERB calls where multiple vocabularies are
returned to use the "by_identifier" scope to ensure that the
vocabularies are sorted.
https://issues.umd.edu/browse/LIBHYDRA-286
=> LIBHYDRA-286. Added "by_identifier" scope to Vocabulary model

app/views/import_jobs/index.html.erb, app/views/vocabularies/index.html.erb
Moved the "New Import Job"/"New Vocabulary" buttons to the the top of
their respective pages, between the page header and table.
https://issues.umd.edu/browse/LIBHYDRA-290
=> LIBHYDRA-290. Moved "New Import Job"/"New Vocabulary" buttons to top

app/controllers/import_jobs_controller.rb, app/models/import_job.rb, app/views/import_jobs/_form.html.erb, app/views/import_jobs/_import_job_info_panel.erb, app/views/import_jobs/index.html.erb, config/locales/en.yml, db/migrate/20200507113214_add_remote_server_to_import_job.rb, db/migrate/20200507151009_import_jobs_file_to_upload_to_metadata_file.rb, db/schema.rb, test/controllers/import_jobs_controller_test.rb, test/fixtures/active_storage/attachments.yml, test/fixtures/active_storage/blobs.yml, test/fixtures/import_jobs.yml, test/models/import_job_test.rb
Updated the new import jobs form to support attaching a binary file, or entering an SFTP string to retrieve the file from a remote server.
Also renamed the "file_to_upload" field in the ImportJob to "metadata_file", to make it more description. A migration has been provided to update entries in the "active_storage_attachments" table.
Note: The binary file option (Option 1) currently does not send anything to Plastron, as the method for doing so is TBD.
https://issues.umd.edu/browse/LIBHYDRA-292
=> LIBHYDRA-292. Added binary source selection to the import jobs

app/models/import_job.rb, app/models/plastron_message.rb, app/views/import_jobs/index.html.erb, db/migrate/20200527202323_add_counts_to_import_job.rb, db/schema.rb
If there is a message body in the status update message, update binary and item count. Also, removed the headers_json method from import_job.
https://issues.umd.edu/browse/LIBHYDRA-299
=> LIBHYDRA-299. Add count fields for import jobs.

lib/tasks/stomp.rake
Updated STOMP connection configuration to use STOMP 1.2.
Modified the STOMP listener to use the "client-individual"
acknowledgement mode for messages received from the "jobs.completed"
queue. Modified the listener to "ack" accepted messages, or to "nack"
messages, if an error occurs.
Added some explanatory comments.
https://issues.umd.edu/browse/LIBHYDRA-261
=> LIBHYDRA-261. Modified stomp.rake to ack/nack "jobs.completed" messages

.env.development, app/assets/javascripts/channels/import_jobs.js, app/controllers/export_jobs_controller.rb, app/controllers/import_jobs_controller.rb, config/initializers/stomp.rb, config/routes.rb, config/stomp.yml, env_example, lib/tasks/stomp.rake
Added "status_update" routes to import and export job controllers which
are called by the STOMP listener to trigger an update message to the
import/export ActionCable channels.
This is needed because the web browser is connected to the Archelon
application, not the STOMP listener, so the "commit" hook in the
ImportJob and ExportJob models that triggers the
ImportJobRelayJob/ExportJobRelayJob has no effect. The "status_update"
routes on the import/export job controllers are called by the STOMP
listener to trigger the ImportJobRelayJob or ExportJobRelayJob, a
appropriate, to send out the update notification to the ActionCable
channels.
Added "ARCHELON_URL" to "env_example", as the STOMP listener needs to
know the URL of the Archelon server to contact.
The "status_update" actions in the …
=> LIBHYDRA-304. Added "status_update" route for STOMP listener

README.md, lib/tasks/add_public_key.rake
Created two Rake tasks in "lib/tasks/add_public_key.rake" - one to take
the public key as a string, the other to read the public key from a
file:
* rails user:add_public_key[cas_directory_id,public_key]
* rails user:add_public_key_file[cas_directory_id,public_key_file]
The tasks assume:
* that the user exists
* the the public key does not exist
* that the public key file is readable
A message will be printed and the task will return with an exit status
of 1 if any of the assumptions are not true.
If the public key is added, a message will be printed, and the exit
status will be 0.
Updated the README.md with a "Rake Tasks" section.
https://issues.umd.edu/browse/LIBHYDRA-307
=> LIBHYDRA-307. Added Rake tasks for adding public keys for users

app/controllers/export_jobs_controller.rb, app/models/export_job.rb, app/services/binaries_stats.rb, app/services/mime_types.rb, app/views/export_jobs/_back_to_new_button.erb, app/views/export_jobs/_summary.html.erb, app/views/export_jobs/job_submission_not_allowed.erb, app/views/export_jobs/new.html.erb, app/views/export_jobs/review.html.erb, config/locales/en.yml, db/migrate/20200611133117_add_mime_types_to_export_jobs.rb, db/schema.rb, test/controllers/export_jobs_controller_test.rb
Modified export jobs to enable only binaries with particular MIME types from being
included in the export.
https://issues.umd.edu/browse/LIBHYDRA-311
=> LIBHYDRA-311. Added MIME type selection to export jobs

app/models/export_job.rb, test/models/export_job_test.rb
Using the Rails ".gigabytes" method for self-documentation.
https://issues.umd.edu/browse/LIBHYDRA-324
=> LIBHYDRA-324. Changed 4 GB to 50 GB limit.

app/services/binaries_stats.rb, app/services/mime_types.rb, app/services/solr_query_service.rb
Added a SolrQueryService base class that implements common functionality between the BinariesStats and MimeTypes classes.
https://issues.umd.edu/browse/LIBHYDRA-325
=> LIBHYDRA-325. Use HTTP POST requests to Solr for service queries.

app/javascript/components/ControlledURIRef.jsx, app/javascript/components/ControlledURIRef.md, app/javascript/components/PlainLiteral.jsx, app/javascript/components/PlainLiteral.md, app/javascript/components/Repeatable.jsx, app/javascript/components/Repeatable.md, app/javascript/components/RepeatableControlledURIRef.jsx, app/javascript/components/RepeatableControlledURIRef.md, app/javascript/components/RepeatablePlainLiteral.jsx, app/javascript/components/RepeatablePlainLiteral.md, app/javascript/components/RepeatableTypedLiteral.md, app/javascript/components/TypedLiteral.jsx, app/javascript/components/TypedLiteral.md, app/models/vocabulary.rb, app/views/react_components/react_components.html.erb
* Gets values from a vocabulary
* Displays as a dropdown
* Renamed param_prefix to paramPrefix (to follow Javascript camelCase conventions)
* Modified input element names so plain literals submit arrays of "{value: '', language: ''}" hashes, and typed literals submit arrays of "{value: '', datatype: ''}" hashes
https://issues.umd.edu/browse/LIBHYDRA-331
=> LIBHYDRA-331. Added ControlledURIRef component.

app/views/export_jobs/new.html.erb
Removed An unmatched </div> tag was causing the footer issues when
test React components were added to the page.
https://issues.umd.edu/browse/LIBHYDRA-328
=> LIBHYDRA-328. Removed extra </div> tag which was causing footer issues

app/services/binaries_stats.rb
This should make the binary size estimates more accurate, as it should include all items selected for export, not just the first 10. Also, removed unneeded "pages" middle-level subquery.
https://issues.umd.edu/browse/LIBHYDRA-334
=> LIBHYDRA-334. Increase the number of rows returned in the binaries_stats query.

app/services/binaries_stats.rb
This should make the binary size estimates more accurate, as it should include all items selected for export, not just the first 10. Also, removed unneeded "pages" middle-level subquery.
Backported to M5 from https://issues.umd.edu/browse/LIBHYDRA-334
https://issues.umd.edu/browse/LIBHYDRA-336
=> LIBHYDRA-336. Increase the number of rows returned in the binaries_stats query.

app/views/resource/edit.html.erb
This was renamed from param_prefix to better align the React components to Javascript naming conventions.
https://issues.umd.edu/browse/LIBHYDRA-338
=> LIBHYDRA-338. Fixed paramPrefix key.

app/models/export_job.rb, env_example
Modified ExportJob so that MAX_ALLOWED_BINARIES_DOWNLOAD_SIZE is
configurable via the .env file.
Updated the "env_example" file with a default size of 50 gigabytes.
https://issues.umd.edu/browse/LIBHYDRA-335
=> LIBHYDRA-335. Make MAX_ALLOWED_BINARIES_DOWNLOAD_SIZE configurable

app/controllers/catalog_controller.rb, app/views/mirador/_show.html.erb, test/controllers/catalog_controller_test.rb
Hide the "Edit Metadata" link when the document "component" is "Page"
or "Article".
https://issues.umd.edu/browse/LIBHYDRA-346
=> LIBHYDRA-346. Hide "Edit Metadata" link for non-top-level components

app/javascript/components/ControlledURIRef.jsx
Modified "app/javascript/components/ControlledURIRef.jsx" to sort the entries in the "vocab" prop by the "label" for the entry (as the "label" is what is displayed in the dropdown).
Also, in the constructor, provided empty string for the "uri" property if "props.value['@id']" is not defined, to fix the following error in the JavaScript console:
```
Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
in select (at ControlledURIRef.jsx:50)
in ControlledURIRef react-dom.development.js:91
```
https://issues.umd.edu/browse/LIBHYDRA-349
=> LIBHYDRA-349. Sort vocabularies in ControlledURIRef dropdowns

app/controllers/resource_controller.rb, app/helpers/resource_helper.rb, app/javascript/components/PlainLiteral.jsx, app/models/content_models.rb
- Content model is determined in the resource controller by checking the RDF type of the resource to be edited.
- Also added ja-latn to languages dropdown in PlainLiteral.
https://issues.umd.edu/browse/LIBHYDRA-352
=> LIBHYDRA-352. Letter and Poster content models.

app/helpers/resource_helper.rb, app/javascript/components/ControlledURIRef.jsx, app/javascript/components/ControlledURIRef.md, app/javascript/components/LabeledThing.jsx, app/javascript/components/LabeledThing.md, app/javascript/components/PlainLiteral.jsx, app/javascript/components/PlainLiteral.md, app/javascript/components/Repeatable.jsx, app/javascript/components/Repeatable.md, app/javascript/components/TypedLiteral.jsx, app/javascript/components/TypedLiteral.md, app/javascript/components/URIRef.jsx, app/javascript/components/URIRef.md, app/views/react_components/react_components.html.erb
* Renamed "paramPrefix" to "subjectURI"
* Renamed "name" to "predicateURI"
* Fixed a small bug initializing "LabeledThing" in the "get_labeled_thing_value" method of "app/helpers/resource_helper.rb", where the "label" and "sameAs" properties were being initialized with a default empty string value. Modified to populate the properties only if an actual value was available.
https://issues.umd.edu/browse/LIBHYDRA-350
=> LIBHYDRA-350. Rename paramPrefix and name properties in React components

docs/ArchelonDevelopmentEnvironment.md
Added link to the "Installing Prerequisites" document, and information
about running "yarn" to install the JavaScript dependencies.
Also added a note that additional datasets are available in the
"umd-fcrepo-sample-data" repo.
https://issues.umd.edu/browse/LIBHYDRA-355
=> LIBHYDRA-355. Added information about prerequisites, and "yarn"

app/controllers/resource_controller.rb, app/services/stomp_service.rb, app/views/resource/form_submit.html.erb, config/stomp.yml, docs/ArchelonDevelopmentEnvironment.md
Added "synchronous_message" method to "StompServices" which sends a message to Plastron and then blocks until a reply is received, or the timeout expires.
Updated the "ResourceController" class with Simple demonstration of synchronous STOMP messages, using the Plastron "echo" command.
https://issues.umd.edu/browse/LIBHYDRA-353
=> LIBHYDRA-353. Add synchronous message sending/receiving capability to the StompService

app/controllers/resource_controller.rb, app/helpers/resource_helper.rb, app/javascript/components/ControlledURIRef.jsx, app/javascript/components/LabeledThing.jsx, app/javascript/components/PlainLiteral.jsx, app/javascript/components/Repeatable.jsx, app/javascript/components/TypedLiteral.jsx, app/javascript/components/URIRef.jsx, app/views/resource/edit.html.erb, app/views/resource/form_submit.html.erb, package.json, yarn.lock
- track deletes and inserts in the components themselves
- generate a list of N-Triple statements to delete and insert in javascript
- craft the sparql update query from that
- set a default for access type
- use the real rdf:type predicate URI for access type
- added simulate param to simulate submission to plastron
- record completely removed values using the Repeatable component
- place all values in a Repeatable component; for non-repeatable set maxValues to 1
https://issues.umd.edu/browse/LIBHYDRA-356
=> LIBHYDRA-356. Generate a list of deletes and inserts on the edit form

app/javascript/components/PlainLiteral.jsx
In PlainLiteral, changed the "no value"/default value in the "Language"
dropdown from "None" to "", based on feedback at the July 13, 2020
Fedora Implementation Team meeting.
https://issues.umd.edu/browse/LIBHYDRA-360
=> LIBHYDRA-360. Changed default language dropdown from "None" to ""

app/assets/javascripts/resource.js, app/assets/stylesheets/custom.css, app/controllers/resource_controller.rb, app/helpers/resource_helper.rb, app/javascript/components/ControlledURIRef.jsx, app/javascript/components/LabeledThing.jsx, app/javascript/components/PlainLiteral.jsx, app/javascript/components/Repeatable.jsx, app/javascript/components/TypedLiteral.jsx, app/javascript/components/URIRef.jsx, app/views/resource/_error_display.html.erb
Modified the React components to include an HTML "name" attribute on the "primary" input field (generally, the textbox for user input). This "name" attribute is used by a CSS selector to find the field when its style needs to be changed due to a validation error.
Modified the "displayErrors" method in "app/assets/javascripts/resource.js" to set a CSS class of "validationError" on fields that have a validation error.
Modified "app/controllers/resource_controller.rb" to parse the errors coming back from Plastron into a map, and provide that map to JavaScript for use by the "displayErrors" method.
https://issues.umd.edu/browse/LIBHYDRA-364
=> LIBHYDRA-364. Improve update error display

app/javascript/components/PlainLiteral.jsx
The "http://www.europeana.eu/schemas/edm/hasType" being used for the "Resource Type" field in Prange Posters can have either a literal value (has an "@value" property), or a URIRef (has an "@id" property). The "PlainLiteral" React component is being used for the field.
Fixed this issue by adding special handling of the "http://www.europeana.eu/schemas/edm/hasType" predicate in the "PlainLiteral" React component. Made the changes in the React component because the SPARQL update to send to Plastron needs to know if the field originated as a literal or as a URIRef.
Since a URIRef does not support a language, broke out the language dropdown into its own component, and modified PlainLiteral to not display the dropdown if a URIRef is being displayed.
Note: As with TypedLiteral in LIBHYDRA-362, …
=> LIBHYDRA-370. Modified PlainLiteral to handle Literal or URIRef

app/controllers/resource_controller.rb, app/helpers/blacklight_helper.rb, app/services/resource_service.rb, test/services/resource_service_test.rb
Created utility methods "display_title" and "sort_titles_by_language" in
"app/services/resource_service.rb" to generate a display title from a
resource (the title is assumed to use the
"http://purl.org/dc/terms/title" predicate). The titles are sorted by
language, to ensure that a consistent order when there are multipl
titles.
Used "app/helpers/blacklight_helper.rb" to override two Blacklight
helper methods to use the ResourceServices utility methods to generate
the title. If the title cannot be generated, the default Blacklight
methods (which use Solr) are used.
This causes the resource detail page to immediately display the correct
title after it has been editing, instead of waiting for Solr to process
the change.
https://issues.umd.edu/browse/LIBHYDRA-366
=> LIBHYDRA-366. Override Blacklight helper methods to display Fedora title

config/environments/development.rb
https://issues.umd.edu/browse/LIBHYDRA-392
=> LIBHYDRA-392. Serve *.json public files as application/ld+json.

.env.development, config/database.yml
Define a SQLite default in .env.development for the development environment. The test database is still configured to always use a SQLite database.
https://issues.umd.edu/browse/LIBHYDRA-402
=> LIBHYDRA-402. Get development database info from environment.

app/controllers/import_jobs_controller.rb, app/models/import_job.rb, app/services/import_job_request.rb, config/imports.yml, docs/ArchelonDevelopmentEnvironment.md, test/models/import_job_test.rb, test/services/import_job_request_test.rb, test/test_helper.rb
Modified Archelon to provide "structure" and "relpath" arguments the import request message sent to Plastron.
This enables collections with "hierarchical" layouts to be loaded via Archelon.
https://issues.umd.edu/browse/LIBHYDRA-410
=> LIBHYDRA-410. Enable Archelon to specify structure and relpath in import

docs/ArchelonDevelopmentEnvironment.md
Updated the "docs/ArchelonDevelopmentEnvironment.md" instructions to
use Python v3.6.12 instead of v3.6.2.
https://issues.umd.edu/browse/LIBFCREPO-969
=> LIBFCREPO-969. Update development env instructions for Python v3.6.12

docs/ArchelonDevelopmentEnvironment.md
In "docs/ArchelonDevelopmentEnvironment.md" update the 'Using the
"postgresql" adapter with Action Cable" in the "development"
environment' section to reflect the current Docker images.
https://issues.umd.edu/browse/LIBHYDRA-417
=> LIBHYDRA-417. Updated "postgresql" adapter with Action Cable" section

app/models/export_job.rb, app/models/search_builder.rb, app/views/catalog/_select_box.erb
Assume an object is exportable unless it is a Page, Article, Collection, or binary.
https://issues.umd.edu/browse/LIBHYDRA-420
=> LIBHYDRA-420. Reverse the exportable type check logic.

config/cable.yml
As the "postgres" ActionCable adapter cannot gracefully handle
Postgres terminating the database connection, switching to using
the in-memory "async" adapter.
While the documentation indicates that the "async" adapter is only for
development/testing (because it does not persist, doesn't scale, and may
not be reliable), it is likely sufficient for our current use case of
using it to process status updates.
https://issues.umd.edu/browse/LIBHYDRA-415
=> LIBHYDRA-415. Switch ActionCable adapter to "async"

app/assets/stylesheets/umd_lib_environment_banner.scss, app/helpers/umd_lib_environment_banner_helper.rb, test/helpers/umd_lib_environment_banner_helper_test.rb
Refactored the "environment banner" implementation to better support use
in Kubernetes. Largely followed the approach taken in umd_lib_style
PR #14 (https://github.com/umd-lib/umd_lib_style/pull/14), where the
following variables are available for setting the banner:
* ENVIRONMENT_BANNER - the text for the banner
* ENVIRONMENT_BANNER_BACKGROUND - The background color of the banner
(in CSS notation)
* ENVIRONMENT_BANNER_FOREGROUND - The foreground color of the banner
(in CSS notation)
* ENVIRONMENT_BANNER_ENABLED - "true" (or present, but blank) if the
banner should be enabled. Any other (non-empty) value is treated as
false
Automatic configuration of the banner based on the hostname (i.e., the
autodiscovery of "dev" and "stage" servers), is no longer provided).
The local development …
=> LIBHYDRA-433. Refactored environment banner for Kubernetes

app/javascript/components/ControlledURIRef.jsx, app/javascript/components/ControlledURIRef.md, app/views/react_components/react_components.html.erb
Modified the ControlledURIRef React component to display a URI that is
not in the vocabulary simply as the URI, instead of showing a blank
value.
The non-vocabulary term is added to the drop-down list, as so will be
available to the user, at least until the field is submitted with a
different value.
https://issues.umd.edu/browse/LIBHYDRA-377
=> LIBHYDRA-377. Updated ControlledURIRef to display non-vocabulary terms

config/initializers/mime_types.rb
The vocabulary files are served from a "public" directory. Configured
Rails to return files using the expected MIME type, based on the
extension.
https://issues.umd.edu/browse/LIBHYDRA-428
=> LIBHYDRA-428. Added MIME types for files in "public" directory

docker-archelon-template.env, docker-compose.yml
Configured the "docker-archelon-template.env" file to use the
"/fcrepo/rest" endpoint that is now used for the Docker setup.
https://issues.umd.edu/browse/LIBFCREPO-1041
=> LIBFCREPO-1041. Configured docker-archelon-template.env for /fcrepo/rest

docker-archelon-template.env, docker-compose.yml
Addd "archelon-sftp" container to "docker-compose.yml". Added
"archelon-import-export-data" volume, used by both the "archelon" and
"archelon-sftp" containers to manage SFTP imports.
Updated the import/export environment variables to reflect their
actual location in the Docker environment.
https://issues.umd.edu/browse/LIBFCREPO-1037
=> LIBFCREPO-1037. Updated Docker config to support SFTP

env_example
Updated the "env_example" file with default
"VOCAB_LOCAL_AUTHORITY_BASE_URI" and "VOCAB_PUBLICATION_BASE_URI"
values, so that they do not need to be added by the user.
This simplifies the installation when setting up Archelon locally.
https://issues.umd.edu/browse/LIBHYDRA-448
=> LIBHYDRA-448. Added default "VOCAB" values to "env_example"

app/assets/javascripts/channels/export_jobs.js, app/channels/export_jobs_channel.rb, app/views/export_jobs/_export_job_status.erb, app/views/export_jobs/_export_job_table_row.erb, app/views/export_jobs/index.html.erb
Largely followed the import status example in LIBHYDRA-446.
One issue was that the "status" field in the "_export_job_status.erb"
helper actually consists of two "td" elements – one for the status,
the other for the "Download" button. This made it problematic to update
the status because targeting the "td" element for the "status" field for
updates resulted in nesting both "td" elements from the helper in a
single "td" element in the table (because the HTML attribute being used
to locate the element in JavaScript was inside the first "td" element).
Ideally, it would have been nice to be able to group the two "td"
elements within a single HTML element that had an attribute that could
be targeted by JavaScript so that they could be replaced together, but
I could not find a way to do this. …
=> LIBHYDRA-449. Update export job status dynamically without page reload

app/assets/javascripts/channels/import_jobs.js, app/controllers/import_jobs_controller.rb, app/services/import_job_info.rb, app/views/import_jobs/_form.html.erb, app/views/import_jobs/_import_job_info_panel.erb, app/views/import_jobs/_import_job_status.erb, app/views/import_jobs/import_job_info_panel/_invalid.erb, app/views/import_jobs/index.html.erb, app/views/import_jobs/show.html.erb, test/controllers/import_jobs_controller_test.rb
- reuse the invalid items panel as the validation report before import
- ensure that the currently selected binaries location is selected when editing an import job
- when a metadata file is uploaded, purge and reattach to ensure the file in ActiveStorage is the one the user uploaded
- dynamically update the item and binaries counts
- display the name of the current metadata file attachment on the resubmit page; use this file if no other file is selected
https://issues.umd.edu/browse/LIBHYDRA-447
=> LIBHYDRA-447. Add invalid items tab panel to import job view.

Dockerfile, docker-compose.yml
The Archelon Dockerfile had the following line to run the "assets:precompile" task:
```
RUN PROD_DATABASE_ADAPTER=postgresql bundle exec rails assets:precompile
```
The "PROD_DATABASE_ADAPTER" environment variable was believed to be needed for the "assets:precompile" task to successfully run, but there is no other reference to the "PROD_DATABASE_ADAPTER" variable anywhere else in the codebase. This was likely copy-and-pasted from some other Rails application (such as "student-applications").
The environment variable has been in the codebase for quite some time,
but was apparently unused. When the "delayed_job" gem was added in
LIBHYDRA-462, the "assets:precompile" task started causing the following
error when building the Docker image:
```
> [8/8] RUN bundle exec rails assets:precompile: …
```
=> LIBHYDRA-467. Added Archelon delayed jobs worker process to Docker Compose stack

app/services/mime_types.rb
The fields used in the solr subquery needs to be explicitly included in the main query 'fl' param.
https://umd-dit.atlassian.net/browse/LIBDEVOPS-229
=> LIBDEVOPS-229. Fix solr query for job binaries.

app/models/plastron_message.rb
Update parse_error method to handle empty body_json when there is a PlastronJobError
https://umd-dit.atlassian.net/browse/LIBHYDRA-521
=> LIBHYDRA-521. Display plastron job error.

README.md
Added a new section for the VSCode Dev Container setup, and noted that it should be used in the meantime
https://umd-dit.atlassian.net/browse/LIBHYDRA-539
=> LIBHYDRA-538: Updated Instructions for setting up Archelon locally.

app/controllers/bookmarks_controller.rb
Disabling the option to email selected items in Archelon since it is not functioning properly
https://umd-dit.atlassian.net/browse/LIBHYDRA-519
=> LIBHYDRA-519: Disabling email functionality

app/assets/javascripts/select_all.js
- The select_all checkbox should be disabled if there are no item with select box on the result page.
- The select_all should be selected only there are items with select box and none are unchecked.
https://umd-dit.atlassian.net/browse/LIBHYDRA-541
=> LIBHYDRA-541. Update select_all behavior.

.devcontainer/devcontainer.json, .env.development, .gitignore
- only forward port 3000 (for the Archelon webapp)
- set the EXPORT_BASE_DESTINATION to an exports directory in the local workspace
- attach to the umd-fcrepo_default network, so that we can use the docker compose service names (repository, activemq, solr-fedora4, etc.)
- update .gitignore to ignore vendored bundles
https://umd-dit.atlassian.net/browse/LIBHYDRA-543
=> LIBHYDRA-543. Improve devcontainer definition.

app/services/resource_service.rb
To get around problems with building a string from response body content when the "frozen_string_literal: true" pragma is in effect, start with an unfrozen empty string (created using the unary '+' operator), then accumulate the body chunks.
https://umd-dit.atlassian.net/browse/LIBHYDRA-545
=> LIBHYDRA-545. Workaround to fix response body retrieval problems.

app/views/mirador/_show.html.erb
On the item detail page:
* Changed the styling of the “Edit Metadata” link to appear as a button; used a white interior to differentiate it from the “Publish” button
* Removed the “Publish Hidden” button
https://umd-dit.atlassian.net/browse/LIBHYDRA-559
=> LIBHYDRA-559. Item detail page button updates.

app/views/mirador/_show.html.erb
This ensures that Pages or Articles do not have the publish buttons appear for them.
https://umd-dit.atlassian.net/browse/LIBHYDRA-568
=> LIBHYDRA-568: Moving publish buttons underneath the check for metadata

app/javascript/components/ControlledURIRef.jsx
1) Modified the ControlledURIRef React component to disable the hidden
"insert" field when the user selects the "empty" option in drop-down
list.
This is done so that when the "empty" option is chosen, the
generated SPAQRL only contains a "DELETE" statement.
Prior to this change the SPARQL query should generate both a "DELETE"
statement, and an "INSERT" statement of the form:
```
INSERT { <subjectURI> <predicateURI> <> . }
```
which resulted in the <subjectURI> being used for the node field.
This change fixes the validation issue seen in Plastron, because no
value is being inserted, so validator that checks whether the new value
is in the vocabulary is not triggered.
2) Modified the ControlledURIRef component to remove a duplicate "empty"
option that occurs when the initial value of field …
=> LIBHYDRA-572. Updated ControlledURIRef to handle unsetting value

app/views/catalog/_show_default.html.erb
Some items have tens or hundreds of "pcdm:members" (such as <https://archelon.lib.umd.edu/catalog/https:%2F%2Ffcrepo.lib.umd.edu%2Ffcrepo%2Frest%2Fdc%2F2023%2F1%2F31%2F26%2F3f%2F35%2F31263f35-6122-47d7-8c95-5566e5cbdee5>)
Since appears to be a "one-off" display issue, implemented the display handling within the "_show_default.html.erb" file itself, instead of doing anything fancier. The initial display limit of "8" is also hard-coded for the same reason.
In the "_show_default.html.erb" file, split the "pcdm_members" subset array into an "initial" list of (up to) 8 items, and a "more" list for any additional items. The "initial" list is display normally as "<li>" items in a "<ul>" unordered list.
If the "more" list has items, an HTML "Details disclosure" element is used with a "summary" of …
=> LIBHYDRA-77. Limit initial number of pcdm:members displayed

.env.development, README.md
Updated the following environment variables in the ".env.development" configuration file with default values for a Docker-based Archelon interacting with a workstation-local Plastron:
* FCREPO_BASE_URL
* PLASTRON_REST_BASE_URL
Added "IMPORT_BINARIES_BASE_LOCATION" environment variable with default value, to support importing binaries via Archelon.
https://umd-dit.atlassian.net/browse/LIBHYDRA-578
=> LIBHYDRA-578. Updated .env.development for Docker-based Archelon

app/controllers/catalog_controller.rb, app/views/catalog/_zero_results.html.erb, config/locales/blacklight.en.yml, test/controllers/catalog_controller_test.rb, test/controllers/publish_jobs_controller_test.rb, test/helpers/umd_lib_environment_banner_helper_test.rb, test/test_helper.rb
- Support identifier search.
- Added test to verify redirect behavior for successful identifier search.
- Set MT_KWARGS_HACK in test_helper to workaround Minitest stubbing issues with Ruby 2.7
- Refactored PublishJobsControllerTest to use stubbing instead of monkey patching.
https://umd-dit.atlassian.net/browse/LIBHYDRA-550
=> LIBHYDRA-550. Identifier search implementation

.env.development, app/helpers/application_helper.rb, app/helpers/resource_helper.rb, app/views/catalog/_show_default.html.erb, config/content_models.yml, env_example, test/fixtures/files/sample_vocabularies/form.json, test/helpers/application_helper_test.rb, test/helpers/resource_helper_test.rb
Modified Archelon to display a "Handle" field on the item detail page when an item has a handle.
Implemented as follows:
* The "get_field_values" method in "resource_helper.rb" was not properly distinguishing item values based on the predicate and datatype. Instead, it would return all the values for a given predicate, irrespective of its datatype (meaning that if two fields had the same predicate, but different datatypes, each field would get both values).
In fixing the "get_field_values" method to properly distinguish between datatypes, the "uri_to_fieldname" method turned out to be unnecessary, and the method signature itself was changed to only require an "item" parameter, and a "field" parameter (so both the field's predicate and datatype (if present) could be queried).
Updated the …
=> LIBHYDRA-571. Display the "Handle" field in Archelon

Jenkinsfile, lib/tasks/stomp.rake
- Removed ack/nack calls from the progress messages. Messages in ActiveMQ topics can't be acked or nacked.
- Ignore synchronous jobs in the progress topic listener.
https://umd-dit.atlassian.net/browse/LIBHYDRA-516
=> LIBHYDRA-516. Additional STOMP listener fixes.

app/views/download_urls/generate_download_url.html.erb
Modified the "Cancel" button on the "Generate Download URL" page to return to the binary detail page from which is came.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1409
=> LIBFCREPO-1409. "Cancel" on "Generate Download URL" goes to binary page

config/content_models.yml
Added optional "copyright_notice" field to the Item, Letter, Poster, and Issue models, so that a "Copyright Notice" field is displayed on the item detail page, and as an editable field on the metadata edit page.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1423
=> LIBFCREPO-1423. Add optional "copyright_notice" field to content models

config/content_models.yml
Changed the "schema" prefix from "http://schema.org/" to "https://schema.org/" as "https" is the protocol used in the canonical URLs on the schema.org website.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1431
=> LIBFCREPO-1431. Changed "schema" prefix to "https://schema.org/"

app/views/catalog/_show_sidebar.html.erb
Uses the display_title rather than hardcoding the name and page number
https://umd-dit.atlassian.net/browse/LIBFCREPO-1411
=> LIBFCREPO-1411: Updating the names for the hyperlinks

config/content_models.yml
Added optional "terms_of_use" field to the Item, Letter, Poster, and Issue models, so that a "Terms of Use" field is displayed on the item detail page, and as an editable field on the metadata edit page.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1429
=> LIBFCREPO-1429. Add optional "terms_of_use" field to content models

app/services/vocabulary_service.rb, test/fixtures/files/sample_vocabularies/README.md, test/fixtures/files/sample_vocabularies/access.json, test/fixtures/files/sample_vocabularies/form.json, test/fixtures/files/sample_vocabularies/rightsStatement.json
Modified the "vocab_options_hash" method in
"app/services/vocabulary_service.rb" to filter out any entries where the URI exactly matches the URI of the vocabulary.
This is done so that the dropdown options do not contain an extraneous option related to the name of the vocabulary itself.
Updated the following vocabulary test fixtures, based on the current results from the "vocab.lib.umd.edu" server:
* test/fixtures/files/sample_vocabularies/access.json
* test/fixtures/files/sample_vocabularies/form.json
* test/fixtures/files/sample_vocabularies/rightsStatement.json
Did not update "one_term_vocabulary.json", because the "collection" vocabulary on the "vocab.lib.umd.edu" server now has more than one term.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1430
=> LIBFCREPO-1430. Remove vocab URI label from dropdown options

app/services/vocabulary_service.rb, test/services/vocabulary_service_test.rb
* In “test/services/vocabulary_service_test.rb”, replaced "vocab_hash" in test names with "vocab_options_hash", as that is more descriptive of what is being testedAlso renamed "vocab_hash" local variable in the tests to "vocab_options_hash" to be more consistent.
* In “app/services/vocabulary_service.rb“, Moved the parsing of vocabulary "graph" objects into the "parse_graph" method to enable the filtering out any "term" that has a "uri" that exactly matches the URL of the vocabulary being downloaded. This removes the extraneous the self-identifying vocabulary term.
* In the "vocab_options_hash" method, removed the filtering of the self-identifying vocabulary term, as it is no longer needed.
*  In the “parse_graph” method, specifically decided to pass the vocabulary identifier to the …
=> LIBFCREPO-1439. Remove extraneous entry from "Access" field on "New Import Job" page

config/content_models.yml, test/services/vocabulary_service_test.rb
Removed the "access" field from the Item, Poster, Letter, and Issue content models. This remotes the "Access Level" field from the item metadata edit page.
Updated the "test/services/vocabulary_service_test.rb", which was using the "access" field from the content model in one of the tests to use a locally-generated example of the field.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1440
=> LIBFCREPO-1440. Removed "Access Level" field from metadata edit page

app/controllers/catalog_controller.rb, config/locales/en.yml
To better align with current terminology, relabelled "Collection" to "Administrative Set" in the following places:
1) The "Limit your Search" facet display in the left sidebar on the
search page - "app/controllers/catalog_controller.rb"
2) The "New Import Job" form - "config/locales/en.yml"
https://umd-dit.atlassian.net/browse/LIBFCREPO-1444
=> LIBFCREPO-1444. Changed "Collection" to "Administrative Set" in GUI

app/controllers/catalog_controller.rb
In “app/controllers/catalog_controller.rb”, modified the facets in the
“Limit your Search” sidebar, so that:
* The “Presentation Set” facet is at the top of the list, and shown as
“open” by default.
* The “Administrative Set” facet has been moved to the second position,
and is "closed" by default.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1445
=> LIBFCREPO-1445. Show "Presentation Set" facets at all times in Archleon

app/assets/javascripts/application.js
Removed the "jquery_ujs" JavaScript dependency, which should have been removed as part of the Rails 4 to Rails 5 migration (it was replaced in Rails 5 with the "rails-ujs" dependency).
This has done (as suggested in https://stackoverflow.com/a/55239361) to fix the "data-confirm" confirmation dialog pop appearing twice.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1448
=> LIBFCREPO-1448. Removed "jquery_ujs" to fix doubled confirmation popup

db/migrate/20240627182231_drop_vocabulary_tables.rb, db/schema.rb
Added a database migration to drop the following Vocabulary-related database tables:
* datatypes
* individuals
* types
* vocabularies
Ran `rails db:migrate` to update the "db/schema.rb" file.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1369
=> LIBFCREPO-1369. Drop Vocabulary-related database tables

app/views/catalog/_show_default.html.erb, config/content_models.yml, docs/ContentModelDefinitions.md
Added an optional "edit_only" field to the content model definition to enable specific fields, such as "Presentation Set" to not be displayed on the item detail page.
This is needed because otherwise the "Presentation Set" field would be shown twice on the item detail page -- once for the Solr-based field specified in the “app/controllers/catalog_controller.rb” configuration and once for the Fedora-based field specified in the “config/content_models.yml” file.
Based on June 26, 2024 WebEx discussions in the “Fedora” channel with Josh Westgard, the preference is to display the Solr field on the item detail page because:
> ... that way we know that the update has "stuck" all the way throughthe stack. So even though there is a delay associated with making such a change, in the long run this …
=> LIBFCREPO-1458. Added optional "edit_only" content model field

app/javascript/components/ControlledURIRef.jsx, app/views/catalog/_show_default.html.erb, config/content_models.yml, docs/ContentModelDefinitions.md
In LIBHYDRA-356, a "componentWillUnmount" method was added to the React
components to support deletion when used with the "Repeatable" React
component. The "ControlledURIRef" component apparently missed in the
update.
Added the "componentWillUnmount" to fix the issue with deleting entries
when the "ControlledURIRef" component is used with a "Repeatable" React
component.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1460
=> LIBFCREPO-1460. Fix "ControlledURIRef" delete when "Repeatable"

app/controllers/catalog_controller.rb, config/content_models.yml
Have to also change the content_model to make the terms of use from fcrepo only appear in the edit section, so that it doesn't appear twice in the details.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1491
=> LIBFCREPO-1491: Adding terms_of_use_text to catalog_controller

README.md, app/controllers/sessions_controller.rb, app/helpers/cas_helper.rb, config/initializers/omniauth.rb, config/routes.rb
Using CAS authentication for Archelon in the local development environment is problematic because DIT does not allow the “localhost” hostname to communicate with the CAS server.
To work around this, Archelon uses the “archelon-local” hostname in the local development environment.
This works for most Rails functionality, but appears to break Rails ActionCable functionality in Firefox, where the web browser can never subscribe to the ActionCable channels provided by the server.
This implementation uses the OmniAuth “developer” strategy (see <https://github.com/omniauth/omniauth/blob/v1.9.2/lib/omniauth/strategies/developer.rb>) which instead of going to CAS, presents a form with a single “Uid” field.
Note: Because Archelon uses the provided username to pull information from LDAP, only …
=> LIBFCREPO-1551. Implemented OmniAuth "developer" strategy to bypass CAS

README.md, app/channels/application_cable/connection.rb, app/channels/export_jobs_channel.rb, app/channels/import_jobs_channel.rb, app/channels/publish_jobs_channel.rb, app/javascript/application.js, app/javascript/channels/consumer.js, app/javascript/channels/export_jobs_channel.js, app/javascript/channels/import_jobs_channel.js, app/javascript/channels/index.js, app/javascript/channels/publish_jobs_channel.js, app/jobs/export_job_status_updated_job.rb, app/jobs/import_job_status_updated_job.rb, app/jobs/publish_job_status_updated_job.rb, app/views/import_jobs/_import_job_status.erb, app/views/publish_jobs/_publish_job_status.html.erb, docs/ActionCable.md, docs/Archelon2.0MigrationNotes.md, docs/RailsAssetPipeline.md, lib/tasks/stomp.rake, package.json, test/channels/application_cable/connection_test.rb, yarn.lock
Implemented dynamic status updates for import jobs, exports jobs, and
publish jobs using Rails Action Cable.
**Note:** In the local development environment dynamic updates do **not**
work with Firefox. They do work with Chrome and Safari.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1523
=> LIBFCREPO-1523. Dynamic Status Updates for Import/Export/Publish Jobs

app/controllers/application_controller.rb, app/controllers/download_urls_controller.rb, app/javascript/resource.js, app/views/catalog/_show_sidebar.html.erb, app/views/download_urls/index.html.erb, app/views/download_urls/new.html.erb, app/views/download_urls/show.html.erb, app/views/import_jobs/_form.html.erb, app/views/shared/_error_messages.html.erb, config/environments/development.rb, config/routes.rb, test/controllers/download_urls_controller_test.rb, test/controllers/static_pages_controller_test.rb, test/test_helper.rb
* Don't clear out the errorDiv on page load
* Rework download urls forms to operate as expected
- disabled turbo
- use the normal resource routing for download URLs
- fixed tests
* Disable turbo on the import jobs form
- use the shared/error_messages partial to display errors
https://umd-dit.atlassian.net/browse/LIBFCREPO-1608
=> LIBFCREPO-1608. Re-enable error message display for download URL and import job forms.

app/assets/stylesheets/_umd_classes.scss, app/controllers/cas_users_controller.rb, app/helpers/cas_helper.rb, app/views/cas_users/index.html.erb, config/routes.rb, db/migrate/20250324141226_add_active_to_cas_user.rb, db/schema.rb, test/controllers/cas_users_controller_test.rb, test/fixtures/cas_users.yml
* if a user is inactive, they cannot successfully log in
* by default, hide inactive users from the manage users list, but provide a toggle switch to view them
* users cannot deactivate themselves
* only users with permissions to manage users (i.e., admins) can (de)activate other users
https://umd-dit.atlassian.net/browse/LIBFCREPO-1505
=> LIBFCREPO-1505. Added "active" column to cas_user model.

app/models/solr_document.rb, test/models/solr_document_test.rb
Modified the "members_anchor" in "solr_document.rb" to return URLS that link to the Archelon-based pages for the "Members" of the document, instead of to the fcrepo-based pages.
This provides consistency with the "Select Page(s) for More Options" panel in the right sidebar, which also provides link to the pages in Archelon, instead of in fcrepo.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1677
=> LIBFCREPO-1677. Modified SolrDocument for Archelon-based "Members" URLs

app/components/archelon_backlink_component.erb, app/components/archelon_backlink_component.rb, app/controllers/catalog_controller.rb
Created an “ArchelonBacklinkComponent” view component using the]
following files:
* app/components/archelon_backlink_component.rb
* app/components/archelon_backlink_component.erb
The “ArchelonBacklinkComponent” view component takes the fcrepo-based
URI in the configured field and queries Solr for the Solr document with
that URI (the URI is assumed to represent the “container” of the item).
The retrieved Solr document is then processed to create a “backlink” to
the container’s Archelon page:
* The fcrepo URI is used to generate a URL to the Archelon page for the
container (using the “solr_document_url”/”solr_document_path” URL
helpers).
* The human-readable text for the link is generated using the mechanism
specified in the field configuration (which is typically the title of
the …
=> LIBFCREPO-1676. Added "ArchelonBacklinkComponent" view component

app/views/bookmarks/_clear_bookmarks_widget.html.erb
The turbo attributes, in conjunction with the old UJS attributes, were causing the confirmation dialog box to appear twice.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1534
=> LIBFCREPO-1534. Overriding stock "clear bookmarks" template to remove turbo attributes.

app/assets/stylesheets/_umd_classes.scss, app/components/extracted_text_metadata_component.html.erb, app/components/extracted_text_metadata_component.rb, app/controllers/catalog_controller.rb, app/models/solr_document.rb
- changed label from "Text/Keywords" to "Text & Metadata"
- changed identifier search label to "Identifier Lookup"
- in addition to the "q" query parameter, try getting the current query from the session, so it can be passed on to the IIIF manifest server for generating the hit highlight annotations
https://umd-dit.atlassian.net/browse/LIBFCREPO-1682
=> LIBFCREPO-1682. Added full text search to the existing text metadata search.

app/models/solr_document.rb
Correct the field check by the guard clause of the `archival_collection_links` accessor.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1697
=> LIBFCREPO-1697. Restore Archival Collection to details page.

app/controllers/catalog_controller.rb, app/models/solr_document.rb
Adding a facet for subjects, and adding an accessor to hyperlink the subject in the item details page.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1695
=> LIBFCREPO-1695: Add Subject Facet and hyperlink it in item details page
