app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-43

LIBHYDRA-43. Show only pcdm nodes on the blacklight interface.

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb

https://issues.umd.edu/browse/LIBHYDRA-42

LIBHYDRA-42. Added new fields.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBFCREPO-201

LIBFCREPO-201. Show related object property in results view.

---

config/environments/development.rb
config/environments/production.rb
config/environments/vagrant.rb
env_example

https://issues.umd.edu/browse/LIBHYDRA-46

LIBHYDRA-46. Use environment variables for fcrepo and iiif server url.

---

app/controllers/catalog_controller.rb

* Removed the sort by author option.
* Added an explicit relevance option that sorts by score and title
* Renamed "created" to "created (oldest to newest)" and "created Desc" to "created (newest to oldest)"
https://issues.umd.edu/browse/LIBHYDRA-51

LIBHYDRA-51. Update sort options.

---

app/controllers/catalog_controller.rb

The UI now does not show the dropdown as there is only one option.
https://issues.umd.edu/browse/LIBHYDRA-50

LIBHYDRA-50. Commented out all search field options except "All fields".

---

.gitignore

https://issues.umd.edu/browse/LIBHYDRA-60

LIBHYDRA-60. Added precompiled assets directory to gitignore.

---

app/views/catalog/_show_default.html.erb

https://issues.umd.edu/browse/LIBHYDRA-61

LIBHYDRA-61. Hide Mirador view on article detail page.

---

app/helpers/application_helper.rb
app/helpers/blacklight_helper.rb
app/views/catalog/_home_text.html.erb

Also set the application name to "Archelon".
https://issues.umd.edu/browse/LIBHYDRA-49

LIBHYDRA-49. Updated home page text.

---

app/assets/javascripts/static_pages.coffee
app/assets/stylesheets/static_pages.scss
app/controllers/static_pages_controller.rb
app/helpers/static_pages_helper.rb
app/views/_user_util_links.html.erb
app/views/static_pages/about.html.erb
config/routes.rb
test/controllers/static_pages_controller_test.rb

https://issues.umd.edu/browse/LIBHYDRA-48

LIBHYDRA-48. Added About page.

---

app/views/cas_users/_form.html.erb
app/views/cas_users/edit.html.erb
app/views/cas_users/index.html.erb
app/views/cas_users/new.html.erb
app/views/cas_users/show.html.erb

Also cleaned up the form buttons and links.
https://issues.umd.edu/browse/LIBHYDRA-55

LIBHYDRA-55. Changed "CAS Directory" to "Directory ID".

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-72

LIBHYDRA-72. Move RDF facet to bottom

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBFCREPO-255

LIBFCREPO-255. Use tokenized fields for facet.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-73

LIBHYDRA-73. Indicate there are additional hidden facet values.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-74

LIBHYDRA-74. Add sort by last modifed (newest to oldest).

---

app/views/catalog/_show_sidebar.html.erb

https://issues.umd.edu/browse/LIBHYDRA-76

LIBHYDRA-76. Remove "Tools" sidebar widget.

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/custom.css
app/views/shared/_header_navbar.html.erb

* Added customized header navbar template to change logo image from background to img tag.
* Added custom.css to override styles in the basic bootswatch stylesheet.
https://issues.umd.edu/browse/LIBHYDRA-71

LIBHYDRA-71. Style improvements for Archelon.

---

public/robots.txt

https://issues.umd.edu/browse/LIBHYDRA-81

LIBHYDRA-81. Disallow all crawlers.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/umd_lib_environment_banner.scss
app/helpers/umd_lib_environment_banner_helper.rb
app/views/shared/_header_navbar.html.erb
config/initializers/inflections.rb

https://issues.umd.edu/browse/LIBHYDRA-80

LIBHYDRA-80. Added standard UMD Libraries environment banner.

---

app/controllers/cas_users_controller.rb
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/helpers/umd_lib_environment_banner_helper.rb
app/helpers/url_helper.rb
app/models/cas_user.rb
app/views/_user_util_links.html.erb
app/views/cas_users/show.html.erb
app/views/mirador/_show.html.erb
db/seeds.rb
lib/tasks/add_cas_user.rake
test/controllers/static_pages_controller_test.rb

https://issues.umd.edu/browse/LIBHYDRA-84

LIBHYDRA-84. Rubocop cleanup.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-88

LIBHYDRA-88. Search annotations in Archelon

---

app/assets/stylesheets/custom.css
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/helpers/url_helper.rb
app/models/search_builder.rb
app/views/catalog/_show_default.html.erb

https://issues.umd.edu/browse/LIBHYDRA-89

LIBHYDRA-89. Display links to pages for annotations.

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/helpers/url_helper.rb
app/views/mirador/_show.html.erb

https://issues.umd.edu/browse/LIBHYDRA-90

LIBHYDRA-90. Propagate query param to view page and mirador iframe.

---

app/models/search_builder.rb

https://issues.umd.edu/browse/LIBHYDRA-89

LIBHYDRA-89. Use present? to exclude empty query params.

---

app/models/search_builder.rb

https://issues.umd.edu/browse/LIBHYDRA-94

LIBHYDRA-94. Facet filter does not work when search query present.

---

app/views/catalog/_show_default.html.erb

https://issues.umd.edu/browse/LIBHYDRA-95

LIBHYDRA-95. Articles and pages are not sorted in detail view.

---

app/views/mirador/_show.html.erb

https://issues.umd.edu/browse/LIBHYDRA-99

LIBHYDRA-99. Select version 1.1.0 of the Mirador Static viewer.

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/helpers/url_helper.rb
config/environments/test.rb
test/fixtures/cas_users.yml

Added necessary environment variables to "test.rb" environment
Made "test_user" and "admin" user so that authorization tests would
succeed.
https://issues.umd.edu/browse/LIBHYDRA-110

LIBHYDRA-110 Fixed broken tests

---

app/helpers/application_helper.rb
app/views/catalog/_show_default.html.erb

https://issues.umd.edu/browse/LIBHYDRA-115

LIBHYDRA-115. Don't show the blank Mirador viewer space on article pages.

---

app/views/download_urls/show_download_url.html.erb

https://issues.umd.edu/browse/LIBHYDRA-112

LIBHYDRA-112. Fixed text error.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/custom.css
app/views/layouts/blacklight.html.erb
app/views/shared/_footer.html.erb

https://issues.umd.edu/browse/LIBHYDRA-119

LIBHYDRA-119. Web Accessibility Footer.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-128

LIBHYDRA-128. Add "Collection" facet field.

---

app/views/_user_util_links.html.erb
app/views/shared/_footer.html.erb

Link text is now "About Archelon".
https://issues.umd.edu/browse/LIBHYDRA-138

LIBHYDRA-138. Moved "About" link to footer.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-141

LIBHYDRA-141. Expand collection facet by default

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-133

LIBHYDRA-133. Remove object type facet field.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-142

LIBHYDRA-142. Sort collection facet alphabetically

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-134

LIBHYDRA-134. Change label "Component" to "Resource Type"

---

app/views/catalog/_show_sidebar.html.erb

* Added issue -> page and page -> file navigation in separate panels
* Made headings more verbose
* Renamed "Links" to "Administration"
https://issues.umd.edu/browse/LIBHYDRA-136

LIBHYDRA-136. Navigation sidebar improvements.

---

app/helpers/application_helper.rb

https://issues.umd.edu/browse/LIBHYDRA-146

LIBHYDRA-146. Use tr instead of gsub.

---

app/views/_user_util_links.html.erb
app/views/static_pages/help.html.erb
config/routes.rb

Currently links to a Google document Archelon User Guide
https://issues.umd.edu/browse/LIBHYDRA-139

LIBHYDRA-139. Added static "Help" page.

---

app/views/catalog/_show_sidebar.html.erb

https://issues.umd.edu/browse/LIBHYDRA-150

LIBHYDRA-150. Sort pages by page number in navigation sidebar.

---

.dockerignore
Dockerfile
README.md
bin/archelon.sh
config/application.rb

https://issues.umd.edu/browse/LIBHYDRA-144

LIBHYDRA-144. First docker image.

---

app/controllers/catalog_controller.rb

https://issues.umd.edu/browse/LIBFCREPO-322

LIBFCREPO-322. Rename page_issue to containing_issue field.

---

.solr_wrapper.yml
README.md
lib/tasks/solr.rake

https://issues.umd.edu/browse/LIBHYDRA-131

LIBHYDRA-131. Use solr_wrapper with a sample data set.

---

app/views/catalog/_show_sidebar.html.erb

Show a "more »" link and a modal listing all pages if there are more than 8 pages in an item.
https://issues.umd.edu/browse/LIBHYDRA-151

LIBHYDRA-151. Limit the page sidebar to the first 8 pages.

---

app/views/catalog/_show_default.html.erb

https://issues.umd.edu/browse/LIBHYDRA-152

LIBHYDRA-152. Check whether component is nil.

---

Rakefile

https://issues.umd.edu/browse/LIBHYDRA-156

LIBHYDRA-156. Only load solr_wrapper rake tasks in env development or test.

---

Gemfile
Gemfile.lock
app/controllers/cas_users_controller.rb
app/controllers/sessions_controller.rb
app/helpers/cas_helper.rb
app/models/cas_user.rb
config/application.rb
config/environment.rb
config/environments/test.rb
config/initializers/omniauth.rb
config/routes.rb
test/controllers/cas_users_controller_test.rb
test/controllers/catalog_controller_test.rb
test/controllers/download_urls_controller_test.rb
test/controllers/retrieve_controller_test.rb
test/controllers/sessions_controller_test.rb
test/controllers/static_pages_controller_test.rb
test/integration/cas_authorization_test.rb
test/integration/download_urls_index_test.rb
test/test_helper.rb

https://issues.umd.edu/browse/LIBHYDRA-161

LIBHYDRA-161. Switch to omniauth-cas gem.

---

app/controllers/application_controller.rb
app/controllers/download_urls_controller.rb
app/controllers/sessions_controller.rb
app/views/_user_util_links.html.erb
app/views/cas_users/index.html.erb
app/views/cas_users/show.html.erb
config/routes.rb
lib/tasks/sample_data.rake
test/controllers/download_urls_controller_test.rb
test/fixtures/cas_users.yml
test/integration/user_impersonation_test.rb
test/test_helper.rb

https://issues.umd.edu/browse/LIBHYDRA-159

LIBHYDRA-159. Implement user impersonation feature.

---

Gemfile
Gemfile.lock
app/controllers/cas_users_controller.rb
app/views/cas_users/show_history.html.erb
config/environments/development.rb
config/environments/production.rb
env_example

https://issues.umd.edu/browse/LIBHYDRA-170

LIBHYDRA-170. Use Postgres database for reading user history.

---

Jenkinsfile

Added Jenkinsfile so that Jenkins job configuration could be managed
within the repository, instead of within Jenkins.
The "archelon-multibranch-pipeline" has been configured to use this
file.
This Jenkinsfile has testing commented out, as the tests rely on
external servers being available, that are not simulated by Jenkins.
https://issues.umd.edu/browse/LIBHYDRA-145

LIBHYDRA-145. Initial implementation of Jenkinsfile

---

Gemfile
Gemfile.lock
app/assets/javascripts/export_jobs.coffee
app/assets/stylesheets/export_jobs.scss
app/controllers/export_jobs_controller.rb
app/helpers/export_jobs_helper.rb
app/models/export_job.rb
app/views/export_jobs/index.html.erb
app/views/export_jobs/new.html.erb
config/environments/development.rb
config/initializers/stomp.rb
config/routes.rb
config/stomp.yml
db/migrate/20190812194529_create_export_jobs.rb
db/schema.rb
test/controllers/export_jobs_controller_test.rb
test/fixtures/export_jobs.yml
test/models/export_job_test.rb

https://issues.umd.edu/browse/LIBHYDRA-172

LIBHYDRA-172. Export jobs draft.

---

app/assets/javascripts/blacklight/checkbox_submit.js
app/assets/javascripts/select_all.js.coffee
app/assets/stylesheets/application.scss
app/controllers/bookmarks_controller.rb
app/controllers/catalog_controller.rb
app/helpers/cas_helper.rb
app/models/bookmark.rb
app/models/cas_user.rb
app/views/_user_util_links.html.erb
app/views/bookmarks/_document_action.html.erb
app/views/catalog/_document_list.html.erb
app/views/catalog/_index_header_default.html.erb
app/views/catalog/_select_all.erb
app/views/catalog/_select_box.erb
config/locales/blacklight.en.yml
config/routes.rb

https://issues.umd.edu/browse/LIBHYDRA-175

LIBHYDRA-175. Enable selection of search results for export.

---

.rubocop.yml
app/assets/stylesheets/custom.css
app/controllers/export_jobs_controller.rb
app/views/_user_util_links.html.erb
app/views/export_jobs/index.html.erb
lib/tasks/sample_data.rake
lib/tasks/solr.rake
test/controllers/export_jobs_controller_test.rb
test/fixtures/export_jobs.yml

Updated the "Export Queue" page listing the export jobs to match the wireframe.
This included adding columns to the table, and setting the styling for the "Status" field.
Note: A placeholder column has been added for the "Download" link, but is not currently populated, as that functionality has not yet been added.
https://issues.umd.edu/browse/LIBHYDRA-174

LIBHYDRA-174. Update Export Queue listing o match wireframe

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/application.scss
app/controllers/bookmarks_controller.rb
app/controllers/export_jobs_controller.rb
app/views/export_jobs/index.html.erb
app/views/export_jobs/new.html.erb
app/views/export_jobs/review.html.erb
config/locales/en.yml
config/routes.rb

https://issues.umd.edu/browse/LIBHYDRA-173

LIBHYDRA-173. Create ExportJob forms.

---

test/controllers/export_jobs_controller_test.rb

https://issues.umd.edu/browse/LIBHYDRA-173

LIBHYDRA-173. Fixed failing tests.

---

config/database.yml
config/environments/production.rb
config/initializers/stomp.rb
env_example

Updated the Rails configuration files to use Postgres in production.
https://issues.umd.edu/browse/LIBHYDRA-181

LIBHYDRA-181. Added Postgres configuration for production

---

app/controllers/export_jobs_controller.rb
app/views/export_jobs/review.html.erb
config/locales/en.yml

https://issues.umd.edu/browse/LIBHYDRA-189

LIBHYDRA-189. Use ExportJob item_count to track export count.

---

test/controllers/export_jobs_controller_test.rb

https://issues.umd.edu/browse/LIBHYDRA-189

LIBHYDRA-189. Fixed failing tests.

---

config/ldap.yml
env_example

https://issues.umd.edu/browse/LIBHYDRA-191

LIBHYDRA-191. Configure LDAP host and port via .env

---

config/ldap.yml

https://issues.umd.edu/browse/LIBHYDRA-191

LIBHYDRA-191. Fixed group attribute for OpenLDAP.

---

config/initializers/ldap.rb

https://issues.umd.edu/browse/LIBHYDRA-193

LIBHYDRA-193. Configure LDAP encryption for SSL to work.

---

app/controllers/export_jobs_controller.rb
app/models/export_job.rb
app/views/export_jobs/index.html.erb
app/views/export_jobs/new.html.erb

https://issues.umd.edu/browse/LIBHYDRA-195

LIBHYDRA-195. Use MIME type as format header and database value.

---

app/controllers/export_jobs_controller.rb
app/controllers/retrieve_controller.rb
app/models/export_job.rb
app/services/stomp_client.rb
app/views/export_jobs/index.html.erb
config/application.rb
config/environments/test.rb
config/environments/vagrant.rb
config/initializers/ssl.rb
config/routes.rb
config/ssl.yml
db/migrate/20190830175753_add_download_url_to_export_jobs.rb
db/schema.rb
env_example

Requires a version of plastrond that includes the changes from https://issues.umd.edu/browse/LIBFCREPO-701
https://issues.umd.edu/browse/LIBHYDRA-196

LIBHYDRA-196. Implemented downloading of completed export jobs.

---

config/initializers/ssl.rb

https://issues.umd.edu/browse/LIBHYDRA-197

LIBHYDRA-197. Use system default cert store if no CA file is given.

---

config/environments/production.rb

https://issues.umd.edu/browse/LIBHYDRA-198

LIBHYDRA-198. Use updated Javascript Uglifier.

---

app/controllers/export_jobs_controller.rb
app/services/stomp_client.rb

If there is no stomp connection when the export_jobs controller is executing, attempt to reconnect. If it does not succeed, return to the bookmarks index page with an error message.
https://issues.umd.edu/browse/LIBHYDRA-199

LIBHYDRA-199. Check STOMP connection.

---

app/controllers/bookmarks_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-204

LIBHYDRA-204. Select All bug fix.

---

app/views/catalog/_select_all.erb
config/locales/blacklight.en.yml

https://issues.umd.edu/browse/LIBHYDRA-201

LIBHYDRA-201. Selection button names update.

---

config/locales/blacklight.en.yml

https://issues.umd.edu/browse/LIBHYDRA-203

LIBHYDRA-203. Change manage selected items page title.

---

config/environment.rb

https://issues.umd.edu/browse/LIBHYDRA-202

LIBHYDRA-202. Set default email from address.

---

app/controllers/download_urls_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-214

LIBHYDRA-214. Fix redirect for Rails 5.

---

config/puma.rb

https://issues.umd.edu/browse/LIBHYDRA-215

LIBHYDRA-215. Log Puma stdout and stderr to files.

---

Dockerfile.ci
Gemfile
Gemfile.lock
Jenkinsfile

Updated project to support a  "Jenkinsfile" using the "Dockerfile.ci" image for building and
testing the application.
https://issues.umd.edu/browse/LIBITD-1486

LIBITD-1486. Initial implementation of Docker-based Jenkins build

---

.env.development
.gitignore
app/controllers/export_jobs_controller.rb
app/services/stomp_client.rb
app/views/shared/_footer.html.erb
config/application.rb
config/environments/development.rb
config/initializers/ldap.rb
config/initializers/ssl.rb
config/initializers/stomp.rb
config/stomp.yml

Also add version number constant and display version number in footer.
https://issues.umd.edu/browse/LIBHYDRA-223

LIBHYDRA-223. Config cleanup.

---

app/controllers/vocabularies_controller.rb
app/views/vocabularies/_form.html.erb
app/views/vocabularies/show.html.erb
db/migrate/20200205205723_add_description_to_vocabularies.rb
db/schema.rb
test/controllers/vocabularies_controller_test.rb
test/fixtures/vocabularies.yml

https://issues.umd.edu/browse/LIBHYDRA-225

LIBHYDRA-225. Add description field to vocabulary model.

---

app/controllers/individuals_controller.rb
app/controllers/types_controller.rb
app/controllers/vocabularies_controller.rb
app/models/individual.rb
app/models/type.rb
app/models/vocabulary.rb
app/views/individuals/_form.html.erb
app/views/individuals/index.html.erb
app/views/individuals/show.html.erb
app/views/types/_form.html.erb
app/views/types/index.html.erb
app/views/types/show.html.erb
app/views/vocabularies/_form.html.erb
app/views/vocabularies/index.html.erb
app/views/vocabularies/show.html.erb
db/migrate/20200207183911_rename_name_columns.rb
db/schema.rb
test/controllers/individuals_controller_test.rb
test/controllers/vocabularies_controller_test.rb
test/fixtures/individuals.yml
test/fixtures/types.yml
test/fixtures/vocabularies.yml

https://issues.umd.edu/browse/LIBHYDRA-231

LIBHYDRA-231. Rename "name" fields to "identifier".

---

app/views/individuals/_form.html.erb
app/views/individuals/edit.html.erb
app/views/individuals/index.html.erb
app/views/individuals/new.html.erb
app/views/individuals/show.html.erb
app/views/types/edit.html.erb
app/views/types/index.html.erb
app/views/types/new.html.erb
app/views/types/show.html.erb
app/views/vocabularies/edit.html.erb
app/views/vocabularies/index.html.erb
app/views/vocabularies/new.html.erb
app/views/vocabularies/show.html.erb
config/initializers/inflections.rb
config/locales/en.yml

Also reordered columns in the term editing form.
https://issues.umd.edu/browse/LIBHYDRA-232

LIBHYDRA-232. Use i18n to handle form labels consistently.

---

README.md
app/controllers/vocabularies_controller.rb
app/models/vocabulary.rb
app/views/individuals/index.html.erb
lib/tasks/vocab.rake
test/data/collections-bad_columns.csv
test/data/collections-bad_rows.csv
test/data/collections.csv
test/integration/vocabulary_import_test.rb

https://issues.umd.edu/browse/LIBHYDRA-238

LIBHYDRA-238. Added vocab:import rake task.

---

app/models/cas_user.rb
app/models/ldap_user_attributes.rb
test/fixtures/cas_users.yml
test/integration/cas_authorization_test.rb

https://issues.umd.edu/browse/LIBHYDRA-211

LIBHYDRA-211. Always check LDAP and update user info on login.

---

app/models/vocabulary.rb

https://issues.umd.edu/browse/LIBHYDRA-241

LIBHYDRA-241. Add dc:identifier to vocab RDF representation.

---

app/views/cas_users/index.html.erb

https://issues.umd.edu/browse/LIBHYDRA-248

LIBHYDRA-248. Added user groups to the user list view.

---

app/models/ldap_user_attributes.rb
test/models/ldap_user_attributes_test.rb

https://issues.umd.edu/browse/LIBHYDRA-251

LIBHYDRA-251. Ignore case when checking groups for user type.

---

Gemfile
Gemfile.lock

https://issues.umd.edu/browse/LIBHYDRA-254

LIBHYDRA-254. Security fixes for Nokogiri and Puma

---

config/environments/development.rb

https://issues.umd.edu/browse/LIBHYDRA-252

LIBHYDRA-252. Set MIME types for Turtle and N-Triples files.

---

config/locales/blacklight.en.yml

https://issues.umd.edu/browse/LIBHYDRA-218

LIBHYDRA-218. Changed "Manage Selected Items" to "Selected Items".

---

app/controllers/vocabularies_controller.rb
app/jobs/publish_vocabulary_rdf_job.rb
app/jobs/unpublish_vocabulary_rdf_job.rb
app/models/individual.rb
app/models/type.rb
app/models/vocabulary.rb
lib/tasks/vocab.rake

- after the vocabulary or any of its terms or classes are saved, or any of the terms or classes are deleted, to publish the vocabulary
- after the vocabulary is deleted, to delete the RDF files
- simplified the publish_rdf method
https://issues.umd.edu/browse/LIBHYDRA-255

LIBHYDRA-255. Use callbacks to publish vocab.

---

config/same_as_abbreviations.yml

https://issues.umd.edu/browse/LIBHYDRA-256

LIBHYDRA-256. Change https to http in LC authority base URIs.

---

app/assets/stylesheets/custom.css
app/controllers/export_jobs_controller.rb
app/models/export_job.rb
app/models/plastron_operation.rb
app/services/stomp_client.rb
app/views/export_jobs/index.html.erb
db/migrate/20200320152422_create_plastron_operations.rb
db/schema.rb
test/fixtures/export_jobs.yml
test/fixtures/plastron_operations.yml
test/models/plastron_operation_test.rb
test/services/stomp_client_test.rb

- use plastron operation in the export job index view
- store request and response STOMP messages in the PlastronOperation
https://issues.umd.edu/browse/LIBHYDRA-253

LIBHYDRA-253. Added PlastronOperation model.

---

app/assets/stylesheets/custom.css
app/controllers/import_jobs_controller.rb
app/models/import_job.rb
app/views/import_jobs/_form.html.erb
app/views/import_jobs/_import_job_info_panel.erb
app/views/import_jobs/index.html.erb
config/locales/en.yml
db/migrate/20200415170216_add_model_to_import_job.rb
db/schema.rb
test/controllers/import_jobs_controller_test.rb
test/models/import_job_test.rb

Also, distinguish between validation failure (there were invalid fields) and validation error (such as an incorrect model).
https://issues.umd.edu/browse/LIBHYDRA-262

LIBHYDRA-262. Added model field to import_job model.

---

README.md
docs/ArchelonDevelopmentEnvironment.md

Created an "ArchelonDevelopmentEnvironment.md" Markdown page based on
the following Confluence document:
* https://confluence.umd.edu/display/LIB/Archelon+Development+Environment
Added additional steps to handle running the Archelon STOMP server.
Added pointer to the ArchelonDevelopmentEnvironment.md" in the project
README.md.
https://issues.umd.edu/browse/LIBHYDRA-283

LIBHYDRA-283. Converted "Archelon Development Environment" to Markdown

---

app/views/vocabularies/index.html.erb
db/seeds/development.rb
db/seeds/test.rb

- Updated the test seeds to just use the same ones as development.
- Added a count of datatypes per vocabulary to the vocabulary index page.
https://issues.umd.edu/browse/LIBHYDRA-287

LIBHYDRA-287. Added datatype vocabulary to development and test seeds.

---

app/views/import_jobs/_import_job_validation_panel.erb
app/views/import_jobs/edit.html.erb
app/views/import_jobs/index.html.erb
app/views/import_jobs/new.html.erb
app/views/import_jobs/show.html.erb
app/views/shared/_header_navbar.html.erb
app/views/shared/_user_util_links.html.erb
config/locales/en.yml

Also cleaned up the header navbar and user links to use more i18n text.
https://issues.umd.edu/browse/LIBHYDRA-300

LIBHYDRA-300. Use i18n text for all "Import Jobs" occurances in views.

---

docs/ArchelonDevelopmentEnvironment.md

Updated "Archelon Development Environment" documentation to reflect
changes required by LIBFCREPO-802, as well as smaller tweaks to the
instructions.
https://issues.umd.edu/browse/LIBHYDRA-303

LIBHYDRA-303. Updated "Archelon Development Environment" documentation

---

app/assets/javascripts/public_keys.coffee
app/assets/stylesheets/public_keys.scss
app/controllers/application_controller.rb
app/controllers/public_keys_controller.rb
app/helpers/public_keys_helper.rb
config/routes.rb
test/controllers/public_keys_controller_test.rb
test/fixtures/cas_users.yml
test/fixtures/public_keys.yml

https://issues.umd.edu/browse/LIBHYDRA-306

LIBHYDRA-306. Create public keys list view

---

.gitignore
app/controllers/import_jobs_controller.rb
app/models/import_job.rb
app/views/import_jobs/_form.html.erb
app/views/import_jobs/_import_job_info_panel.erb
app/views/import_jobs/index.html.erb
config/imports.yml
config/initializers/imports.rb
db/migrate/20200603185929_rename_remote_server_column.rb
db/schema.rb
test/fixtures/import_jobs.yml
test/models/import_job_test.rb

- expand import config to include base location for binaries
- construct binaries location from env var and selected file
- removed manual sftp input and file upload controls
https://issues.umd.edu/browse/LIBHYDRA-298

LIBHYDRA-298. Implement dropbox style input for binaries import.

---

app/controllers/export_jobs_controller.rb
app/controllers/import_jobs_controller.rb

https://issues.umd.edu/browse/LIBHYDRA-319

LIBHYDRA-319. Fix status_update methods to return 204 No Content.

---

README.md
config/application.rb
config/environments/development.rb
config/environments/production.rb
env_example

https://issues.umd.edu/browse/LIBHYDRA-327

LIBHYDRA-327. Default to DEBUG logging in development, and INFO elsewhere.

---

.gitignore
.rubocop.yml
Dockerfile.ci
Jenkinsfile
README.md
app/javascript/components/LiteralValue.jsx
app/javascript/components/LiteralValue.md
app/javascript/components/TextField.jsx
app/javascript/components/TextField.md
app/javascript/packs/application.js
app/views/layouts/blacklight.html.erb
app/views/static_pages/about.html.erb
package.json
styleguide.config.js
yarn.lock

Created a repeatable literal value input field with language tag by creating two React components, "TextField" and "LiteralValue".
The "TextField" component allows multiple "LiteralValue" components to be added/removed.
The "LiteralValue" component consists of a textbox and language dropdown list.
https://issues.umd.edu/browse/LIBHYDRA-314

LIBHYDRA-314: Created repeatable literal value input field with language tag

---

.gitignore
app/controllers/export_jobs_controller.rb
app/models/export_job.rb
app/views/export_jobs/_export_job_status.erb
app/views/export_jobs/index.html.erb
config/exports.yml
config/initializers/exports.rb
db/migrate/20200624191518_remove_download_url_from_export_jobs.rb
db/schema.rb

All exports are now zipped BagIt bags.
https://issues.umd.edu/browse/LIBHYDRA-321

LIBHYDRA-321. Support single-file export.

---

app/views/export_jobs/_export_job_status.erb

https://issues.umd.edu/browse/LIBHYDRA-332

LIBHYDRA-332. Only display download button if there is an export file to download.

---

app/controllers/resource_controller.rb
app/views/mirador/_show.html.erb
app/views/resource/edit.html.erb
app/views/resource/form_submit.html.erb
config/routes.rb

A minimally functional ResourceController implementation that only
shows "Title" and "Date" fields.
https://issues.umd.edu/browse/LIBHYDRA-316

LIBHYDRA-316. Minimal ResourceController implementation

---

app/javascript/components/Repeatable.jsx
app/javascript/components/Repeatable.md
app/javascript/components/URIRef.jsx
app/javascript/components/URIRef.md
app/views/react_components/react_components.html.erb

Added "URIRef" component, and added to "Repeatable", so that a
repeatable version would also be available.
Added examples to React Stylistguide documentation, and to the
http://localhost:3000/react_components page.
https://issues.umd.edu/browse/LIBHYDRA-344

LIBHYDRA-344. Initial implementation of "URIRef" React component

---

app/controllers/resource_controller.rb
app/helpers/resource_helper.rb
app/javascript/components/LabeledThing.jsx
app/javascript/components/LabeledThing.md
app/models/content_models.rb
app/views/react_components/react_components.html.erb
app/views/resource/_metadata_edit_components.html.erb
app/views/resource/edit.html.erb

- Include embedded object values in LabeledThing.
- Pass all items to the define_react_components helper.
https://issues.umd.edu/browse/LIBHYDRA-333

LIBHYDRA-333. Create LabeledThing composite component.

---

app/helpers/resource_helper.rb
app/javascript/components/LabeledThing.jsx
app/javascript/components/LabeledThing.md
app/javascript/components/Repeatable.jsx
app/javascript/components/Repeatable.md
app/javascript/components/URIRef.jsx
app/views/react_components/react_components.html.erb
package.json
yarn.lock

The "LabeledThing" component was refactored to bring its pre-populated
value initialization more in line with the other components.
Added "LabeledThing" to "Repeatable" component and added React
Styleguidist, and "React Components" page examples.
https://issues.umd.edu/browse/LIBHYDRA-347

LIBHYDRA-347. Made LabeledThing component repeatable

---

app/helpers/resource_helper.rb
app/javascript/components/ControlledURIRef.jsx
app/javascript/components/Repeatable.jsx

https://issues.umd.edu/browse/LIBHYDRA-361

LIBHYDRA-361. Correct rdf:type URI for access level field.

---

app/models/content_models.rb

https://issues.umd.edu/browse/LIBHYDRA-358

LIBHYDRA-358. Make subject field repeatable in Letter and Poster content models.

---

app/javascript/components/TypedLiteral.jsx

A "http://purl.org/dc/terms/identifier" value might be either a
literal (with an "@value" property) or a URIRef (with an "@id")
property. Added special handling to display and delete this field when
a value is a URIRef.
https://issues.umd.edu/browse/LIBHYDRA-362

LIBHYDRA-362. Added special handling to "identifier" field

---

config/content_models.yml

Modified the models to match the Required/Optional/Repeatable settings
in the spreadsheet:
https://docs.google.com/spreadsheets/d/1b7zXCbsydUuhuQYvjVJrBaLHMnl4KVQg9QPw5YSHRP4
https://issues.umd.edu/browse/LIBFCREPO-856

LIBFCREPO-856. Modified the models to match rules in spreadsheet

---

app/helpers/application_helper.rb
app/helpers/resource_helper.rb

https://issues.umd.edu/browse/LIBHYDRA-374

LIBHYDRA-374. Handle cases where the vocab is missing.

---

app/services/repository_collections.rb

https://issues.umd.edu/browse/LIBHYDRA-397

LIBHYDRA-397. Set collection search to return 100 rows.

---

lib/tasks/stomp.rake

Wrapped calls to the Rails database in "with_connection" blocks, as the
existing connection may have been terminated due to infrequent or other
causes. Intended to fix an intermittent error:
PG::UnableToSend: no connection to the server
seen on archelondev.lib.umd.edu
https://issues.umd.edu/browse/LIBHYDRA-403

LIBHYDRA-403. Wrapped database calls in "with_connection" blocks

---

config/stomp.yml
lib/tasks/stomp.rake

https://issues.umd.edu/browse/LIBHYDRA-404

LIBHYDRA-404. Align topic and queue names with Plastron.

---

docs/ArchelonDevelopmentEnvironment.md

Restored use of separate Plastron application (in line with
changes in LIBFCREPO-497, in which the Plastron daemon was
removed from the "umd-fcrepo" Docker stack).
Rewrote instructions, replacing "~/git" with a generic "base
directory" notation, and use of relative directory ".." changes.
Renumbered steps using <step number>.<substep number>, for simpler
referencing.
Fixed Markdown style warnings.
https://issues.umd.edu/browse/LIBHYDRA-405

LIBHYDRA-405. Refactored instructions, restoring local Plastron

---

docs/ArchelonDevelopmentEnvironment.md

Updated the local development environment setup instructions in
"docs/ArchelonDevelopmentEnvironment.md" to reflect use of the
"umd-fcrepo" tracking repository.
https://issues.umd.edu/browse/LIBHYDRA-406

LIBHYDRA-406. Update dev instructions to use "umd-fcrepo" tracking repo

---

README.md
app/controllers/public_keys_controller.rb
test/controllers/public_keys_controller_test.rb

https://issues.umd.edu/browse/LIBHYDRA-407

LIBHYDRA-407. Remove restriction for /public_keys.

---

docs/ArchelonDevelopmentEnvironment.md

Updated the "docs/ArchelonDevelopmentEnvironment.md" file with
information and alternative steps for loading data in a "hierarchical"
layout.
Also removed the "-DskipTests=true" from the umd-camel-processors
Maven command, because the tests are now working.
https://issues.umd.edu/browse/LIBFCREPO-966

LIBFCREPO-966. Added "hierarchical" layout info to dev env instructions

---

app/helpers/resource_helper.rb
app/views/catalog/_show_default.html.erb
config/content_models.yml

https://issues.umd.edu/browse/LIBHYDRA-393

LIBHYDRA-393. Map values to fields with appropriate datatypes.

---

docs/ArchelonDevelopmentEnvironment.md
docs/ArchelonDevelopmentEnvironmentDocker.md

Updated the "docs/ArchelonDevelopmentEnvironment.md" and
"docs/ArchelonDevelopmentEnvironmentDocker.md" instructions for
the "umd-fcrepo-messaging" repository added in LIBFCREPO-1018.
https://issues.umd.edu/browse/LIBHYDRA-427

LIBHYDRA-427. Updated instructions for umd-fcrepo-messaging

---

docs/ArchelonDevelopmentEnvironment.md
docs/ArchelonDevelopmentEnvironmentDocker.md

https://issues.umd.edu/browse/LIBHYDRA-427

LIBHYDRA-427. Added "/fcrepo" context path to repo URLs.

---

app/services/plastron_service.rb
test/services/plastron_service_test.rb

Present more user-friendly error message output versus the raw HTML or exception messages for the common cases.
https://issues.umd.edu/browse/LIBHYDRA-450

LIBHYDRA-450. Improve error handling in the plastron service.

---

app/models/export_job.rb
app/views/export_jobs/_export_job_status.erb

Move most of the complex conditional logic into the ExportJob model.
https://issues.umd.edu/browse/LIBHYDRA-453

LIBHYDRA-453. Improve export job status text handling.

---

app/views/static_pages/help.html.erb

https://issues.umd.edu/browse/LIBHYDRA-480

LIBHYDRA-480. Changed "Archelon User Guide" link to use a handle.

---

app/models/vocabulary.rb

Record the filesystem path each file is being written to.
https://issues.umd.edu/browse/LIBHYDRA-481

LIBHYDRA-481. Added additional logging to writing the vocabularies.

---

Dockerfile.ci
app/models/vocabulary.rb
test/controllers/vocabularies_controller_test.rb
test/integration/vocabulary_import_test.rb
test/services/json_rest_result_test.rb

https://issues.umd.edu/browse/LIBHYDRA-504

LIBHYDRA-504. Bump Ruby version to 2.7.6 in Dockerfile.ci.

---

.env.development
README.md
bin/get_plastron_authorized_keys.sh
config/initializers/stomp.rb
config/vocabularies.yml
docker-archelon-template.env
docs/Prerequisites.md
env_example

https://umd-dit.atlassian.net/browse/LIBFCREPO-1230

LIBFCREPO-1230. Update docs to use archelon-local URL.

---

app/services/binaries_stats.rb

https://umd-dit.atlassian.net/browse/LIBHYDRA-522

LIBHYDRA-522. Include subquery fields in main query fl

---

.devcontainer/devcontainer.json
.env.development
Dockerfile.vscode

https://umd-dit.atlassian.net/browse/LIBHYDRA-537

LIBHYDRA-537: Creating VSCode Dev Container for local development

---

lib/tasks/sample_data.rake

Since that was removed in https://github.com/umd-lib/archelon/pull/304 removing its inclusion in the task
https://umd-dit.atlassian.net/browse/LIBHYDRA-540

LIBHYDRA-540: Removed references to plastron_statuses

---

app/controllers/catalog_controller.rb

https://umd-dit.atlassian.net/browse/LIBHYDRA-530

LIBHYDRA-530. Added publication and discoverability facet fields.

---

app/controllers/import_jobs_controller.rb
app/services/resource_service.rb

https://umd-dit.atlassian.net/browse/LIBHYDRA-544

LIBHYDRA-544. When resubmitting a failed import job, set the resume flag.

---

app/controllers/ping_controller.rb

https://umd-dit.atlassian.net/browse/LIBHYDRA-549

LIBHYDRA-549. Updated ping controller to accurately check whether the db is reachable.

---

app/helpers/resource_helper.rb

`to_hash` --> `as_hash`
https://umd-dit.atlassian.net/browse/LIBHYDRA-551

LIBHYDRA-551. Fixed incorrect method name.

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_show_default.html.erb

https://umd-dit.atlassian.net/browse/LIBHYDRA-561

LIBHYDRA-561. Display presentation set label in detail page.

---

app/controllers/catalog_controller.rb

https://umd-dit.atlassian.net/browse/LIBHYDRA-563

LIBHYDRA-563. Add presentation set facet to search.

---

app/views/publish_jobs/show.html.erb

https://umd-dit.atlassian.net/browse/LIBHYDRA-579

LIBHYDRA-579: Updating check for publication status

---

app/assets/javascripts/select_button_item_view.js
app/assets/stylesheets/application.scss
app/controllers/bookmarks_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_select_all.erb
app/views/catalog/_show_sidebar.html.erb
test/controllers/bookmarks_controller_test.rb

- Select box will be displayed only if item is Exportable.
- Select button will be disabled if max selection limit is reached.
- Refactored BookmarksController create method to check for limit and added tests for it.
- Added 'max_bookmarks_selection_limit' helper to replace hard-coded limit set in multiple locations.
https://umd-dit.atlassian.net/browse/LIBHYDRA-477

LIBHYDRA-477. Add select button to item page.

---

lib/tasks/stomp.rake

To prevent a  job_progress message processing error from stoppong the listener, I'm wrapping it in begin/recue block similar to the job_status message processing setup.
Also, added the send_ack and send_nack for the messages.
https://umd-dit.atlassian.net/browse/LIBHYDRA-516

LIBHYDRA-516. Recue job_progress message processing errors.

---

app/models/publish_job.rb

Makes sure the publish job request get their entries deleted when the associated publish_job is deleted
https://umd-dit.atlassian.net/browse/LIBFCREPO-1424

LIBFCREPO-1424: Adding relation to publish_job_request

---

config/content_models.yml

https://umd-dit.atlassian.net/browse/LIBFCREPO-1436

LIBFCREPO-1436: Updating Legacy models to include handle

---

app/controllers/export_jobs_controller.rb
app/views/export_jobs/_export_job_table_row.erb
app/views/export_jobs/show.html.erb

Adds a detail page for Export Jobs, where there is an option to delete the job.
https://umd-dit.atlassian.net/browse/LIBFCREPO-1389

LIBFCREPO-1389: Adding ability to delete export jobs

---

app/cron_jobs/delete_old_export_jobs_cron_job.rb
app/jobs/delete_old_exports_job.rb
test/jobs/delete_old_exports_job_test.rb

https://umd-dit.atlassian.net/browse/LIBFCREPO-1446

LIBFCREPO-1446: Creating cronjob to delete old export jobs

---

Gemfile.lock
app/javascript/application.js
app/javascript/clipboard.js
app/views/catalog/_show_sidebar.html.erb
app/views/download_urls/_retrieve_url.html.erb
app/views/download_urls/index.html.erb
app/views/download_urls/show.html.erb
app/views/download_urls/show_download_url.html.erb

Re-added ClipboardJS:
* https://clipboardjs.com/
* register a window load event handler on the retrieve URL partial that sets up the copy button
Updates for Bootstrap 5:
* changed "btn-default" to btn-primary
* changed "panel" to "card"
* layout fixup for the display filter form on the download URLs list
* removed "nav" class from download or generate download URL list inside the sidebar card
https://umd-dit.atlassian.net/browse/LIBFCREPO-1532

LIBFCREPO-1532. Re-added ClipboardJS to Download URL page.

---

app/assets/stylesheets/application.scss
app/views/catalog/_home_text.html.erb
app/views/shared/_footer.html.erb
config/application.rb

- added home page welcome text
- added footer template and styling
- added `Archelon::VERSION` constant in application.rb (set to 2.0.0-dev)
https://umd-dit.atlassian.net/browse/LIBFCREPO-1521

LIBFCREPO-1521. Added home page welcome text and footer.

---

db/migrate/20250321140555_set_job_request_foreign_key_options.rb
db/schema.rb
test/jobs/delete_old_exports_job_test.rb

https://umd-dit.atlassian.net/browse/LIBFCREPO-1490

LIBFCREPO-1490. Added cascading delete to job request tables.

---

app/controllers/resource_controller.rb
config/initializers/plastron.rb
test/controllers/resource_controller_test.rb

https://umd-dit.atlassian.net/browse/LIBFCREPO-1647

LIBFCREPO-1647. Use HTTP instead of STOMP for editing metadata.

---

config/content_models.yml

https://umd-dit.atlassian.net/browse/LIBFCREPO-1648

LIBFCREPO-1648: Add Rights Statement to Issue

---

app/controllers/catalog_controller.rb
app/controllers/resource_controller.rb
app/models/solr_document.rb
config/content_models.yml

- added to the catalog controller for display
- added to Item content model for editing
https://umd-dit.atlassian.net/browse/LIBFCREPO-1659

LIBFCREPO-1659. Added Audience field to details and edit form.

---

app/controllers/catalog_controller.rb

Each item should show the following metadata fields
- Title
- Thumbnail Image
- Object Date
- Description
- Resource type
- Number of Pages
- Archival Collection
- Creator
https://umd-dit.atlassian.net/browse/LIBFCREPO-1669

LIBFCREPO-1669: Update metadata fields to display in the search results

---

app/assets/stylesheets/_facets.scss
app/assets/stylesheets/application.scss
app/components/filter_facet_component.html.erb
app/components/filter_facet_component.rb
app/controllers/catalog_controller.rb
app/javascript/application.js
app/javascript/filter_facet.js

Created a new component that can be applied to the facet fields
- The limit shouldn't be specified so that all fields are present
- The css on the list will make it scrollable after it gets too big
- Currently applied to both the Creator and Archival Collection facets
https://umd-dit.atlassian.net/browse/LIBFCREPO-1688

LIBFCREPO-1688: Creation of Component for filtering facets
